### ISSUE TITLE
[question] Is it possible to update aliases without conan install --update?

### ISSUE THREAD

**Issue by jlemein** [conan-io/conan#10074]
I am creating an installer that fetches artifacts from our locally run conan server (that fetches in turn from conan center).
In order to get the latest artifacts I am using aliases. For example:

```python
def build_requirements(self):
    self.build_requires("myapp/(latest)@mycompany/stable")
    self.build_requires("myresources/(latest)@mycompany/stable")
```

The idea is that we want a pipeline to create a new installer package after every change to one of the dependencies, so that we always have the latest installer version.

If I run `conan install ..`, it does not update the alias. Only by running `conan install .. --update` it fetches the latest aliases. 
The nasty consequence we are experiencing at the moment is that it updates also all underlaying dependencies, including the latest revision of `gtest 1.10.0` which is not working for us. The library  CONAN_PKG::gtest cannot be found. I guess this syntax is ill-advised, but it still worked for us with an older revision.

So I am wondering right now, is there a way that I can resolve the latest aliases, without forcing to update all dependencies (i.e. fetch the latest revisions)?
Also using aliases in this way, is that actually recommended?

- [ x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jlemein** [comment]
Also I noticed that `conan install .. --update` is updating build requirements (i.e. gtest for example) for my requirements. Should this happen? I am just planning to fetch the artifacts. No need to build from source.

So what I mean is: Let's say packageA has requirements on packageB1 and packageB2. In turn packageB1 has a build dependency on packageC. In this case I do not expect that packageC get's updated when I run `conan install .. --update` for packageA.

**Comment by memsharded** [comment]
Hi  @jlemein 

I am missing the information on how you are creating, updating, uploading the ``alias``.

You are right, it is possible that ``alias`` is not the best approach. This is a feature that we added long time ago, even before than Conan had version ranges, for example. As a general idea, it is possible that the flow can be simplified with different approaches:
- Have you considered using ``version-ranges`` instead? If you want to depend on the latest from ConanCenter, a version range will do it
- Have you considered pinning the specific versions and revisions of others? For example, for ``gtest 1.10.0``, you can do a ``requires = "gtest/1.10.0#specificrevision``

**Comment by jlemein** [comment]
At the moment we only try to follow development branches using aliases. In our pipeline we call the following methods to create a conan package, the alias and to upload it to our remote.

```python
conan package . --source-folder=. --build-folder="./buildRelease"
conan package . --source-folder=. --build-folder="./buildDebug"
conan export-pkg . @mycompany/unstable --package-folder=buildRelease/package -s build_type=Release
conan export-pkg . @mycompany/unstable --package-folder=buildDebug/package -s build_type=Debug

# version is determined from a script
conan alias mylib/latest@mycompany/unstable mylib/${PACKAGE_VERSION}@mycompany/unstable
conan upload mylib/${PACKAGE_VERSION}@mycompany/unstable --all -c -r mycompany
conan upload mylib/latest@mycompany/unstable --all -c -r mycompany
```
Our development packages are versioned in the postfix. So consecutive builds have the following version numbers:
```python
mypackage/1.0.0-dev.1 #dev.<BUILD_NUMBER>
mypackage/1.0.0-dev.2
mypackage/1.0.0-dev.3
...
```
The version number is a bit nonsense here, but since we have to follow semantic versioning, they are like this for now.
So every day we have a couple of merges to development, causing the postfix to increment.

The major, minor, patch version numbers are untouched for now. I think it is quite a hassle (at the moment) to automatically bump the numbers based on build numbers. But if this is the way to go, I have to revisit the version numbers.

I am willing to use version ranges, but can a version range also look at the postfix?

I think hardcoding to a specific revision is the safest option for now, but it requires me to go through all repositories to check if somebody uses a 'gtest' that can mess up with the cache in the build server.

**Comment by memsharded** [comment]
Yes, pre-releases can also be resolved by version ranges, it is tested in Conan test suite:

```python
 # prereleases are ordered
        result = satisfying(["1.1.1-a.1", "1.1.1-a.11", "1.1.1-a.111", "1.1.1-a.21"], "~1.1.1-a",
                            output)
        self.assertEqual(result, "1.1.1-a.111"


  result = satisfying(["1.0.0-pre"], "~1.0, include_prerelease=True", output)
```

As you see, you might need to opt-in into resolving to prereleases (not matched by semver by default), but using ``-xxx`` in the range, or adding ``include_prerelease=True``

**Comment by jlemein** [comment]
Thanks, so if I understand it correctly it looks as follows:
```
def requirements(self):
        self.requires("myapplication/[>0.1.0-dev, include_prerelease=True]@mycompany/unstable")
        self.requires("some-other-app/[>0.1.0-dev, include_prerelease=True]@mycompany/unstable") 
```
If I look at the result of running `conan install` it seems it does not resolve to the latest available on the remote. It resolves to the latest in my cache. Can I force it to retrieve the latest from the remote in this case? Or are we then back at `conan install --update`?

**Comment by fourbft** [comment]
I don't know, if I understood your problem correctly, but when you wrote:

> If I run conan install .., it does not update the alias.

did you mean that it does not update the alias in the local cache?
Would deleting the alias in the local cache prior to the install help? Because Conan then fetches the alias from the server and thus will pick up the updated aliases. I. e. something like:
```
conan remove -f "*/latest@*"
```
before your `conan install ..,`?

**Comment by AbrilRBS** [comment]
Closing as Conan 1-specific.

Conan 2 dropped support for most alias-releated workflows
