### ISSUE TITLE
[feature] keep searching for recipes, if one server down

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#10384]
In my setup, I have 2 remotes defined - conancenter and artifactory.
If I use command
conan search "zlib" -r all, if one of these two servers is down, the whole command will also fail. I would be better to do it more robust.
The same applies to conan install. If I have a recipe only in artifactory and try to install it (yes, I don't specify -r artifactory), it will fail if conancenter is not accessable.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This is already fixed in Conan 2.0, you can try the released alpha in PyPI (the new ``search`` command).

The ``install`` behavior will not be changed. When installing packages it is very important, sometimes critical that the configured remotes work, or error otherwise. You can always use the ``conan remote disable`` functionality to temporarily disable one remote that is not responding.

**Comment by memsharded** [comment]
As this is apparently already in 2.0-alpha, I think we can close it now as implemented. Thanks for reporting!

**Comment by AndreyMlashkin** [comment]
I would still have some flag to install command, like --ignore-offline or similar

**Comment by memsharded** [comment]
> I would still have some flag to install command, like --ignore-offline or similar

I am sorry, but we will most likely not add something like this, as mentioned above, offline repositories that are skipped could be a problem in some scenarios, so we don't want to add a new cli argument (to basically every Conan command: install, create, export-pkg, build, test) for handling this case. It will be possible to select the remotes you want to use (even more than one) or to ``conan remote disable`` the remotes that you want, but we cannot grow the CLI for every command for every possible situation.
