### ISSUE TITLE
[bug] Error while compiling with bazel: Error in glob: pattern cannot be absolute

### ISSUE THREAD

**Issue by mohabouje** [conan-io/conan#10476]
I reported a bug yesterday: https://github.com/conan-io/conan/issues/10471#issuecomment-1026297628

I've installed master with the fix and it seems to solve that issue.

I'm running into a different issue when using bazel now, It may not be related to that specific commit but its something that breaks in the commits in master planned for version 1.45, as it works just fine in version 1.44.1

### Environment Details (include every applicable attribute)
  * Operating System+version: Fedora release 34 (Thirty Four)
  * Compiler+version: gcc (GCC) 11.0.1 20210324 (Red Hat 11.0.1-0)
  * Conan version: Conan version 1.44.1 
  * Python version: Python 3.9.2

### Steps to reproduce (Include if Applicable)
```
from conans import ConanFile
from conan.tools.google import BazelToolchain, BazelDeps


class ExampleConanIntegration(ConanFile):
    name = "example"
    version = "0.0.1"
    generators = ['BazelDeps', 'BazelToolchain']
    requires = [
        'glew/2.2.0'
    ]

    def configure(self):
          pass

    def imports(self):
          pass
```
Then run:

```
conan install . --build=missing -s compiler=gcc -s compiler.version=11 -s compiler.libcxx=libstdc++11 -s build_type=Debug
```
Try to use the dependencies on any bazel project:

```
bazel build //...
```
It wont compile anymore

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
ERROR: /home/mboujema/Developer/tijara/conandeps/glew/BUILD.bazel:5:10: //conandeps/glew:GLEWd_precompiled: invalid label '/home/mboujema/.conan/data/glew/2.2.0/_/_/package/44741af961cbe3bae7bd261b66459e5b6dc65693/lib/libGLEWd.a' in attribute 'static_library' in 'cc_import' rule: invalid target name '/home/mboujema/.conan/data/glew/2.2.0/_/_/package/44741af961cbe3bae7bd261b66459e5b6dc65693/lib/libGLEWd.a': target names may not start with '/'
ERROR: Traceback (most recent call last):
        File "/home/mboujema/Developer/tijara/conandeps/glew/BUILD.bazel", line 14, column 16, in <toplevel>
                hdrs = glob(["/home/mboujema/.conan/data/glew/2.2.0/_/_/package/44741af961cbe3bae7bd261b66459e5b6dc65693/include/**"]),
Error in glob: pattern cannot be absolute
```

**Comment by mohabouje** [comment]
It has nothing to do with glew, this fails with any package, I've tried boost or fmt.

Version 1.44.1 generate a BUILD:
```

load("@rules_cc//cc:defs.bzl", "cc_import", "cc_library")


cc_import(
    name = "fmtd_precompiled",
    static_library = "lib/libfmtd.a"
)


cc_library(
    name = "fmt",
    
    hdrs = glob(["include/**"]),
    
    
    includes = ["include"],
    
    
    
    visibility = ["//visibility:public"],
    
    deps = [
    
    ":fmtd_precompiled",
    
    ],
    
)
```

Version1.45-devel generates BUILD.bazel:

```

load("@rules_cc//cc:defs.bzl", "cc_import", "cc_library")


cc_import(
    name = "fmtd_precompiled",
    static_library = "/home/mboujema/.conan/data/fmt/8.0.1/_/_/package/20da98908a15523bbe9f086a5c57a4bde424a9c0/lib/libfmtd.a"
)


cc_library(
    name = "fmt",
    
    hdrs = glob(["/home/mboujema/.conan/data/fmt/8.0.1/_/_/package/20da98908a15523bbe9f086a5c57a4bde424a9c0/include/**"]),
    
    
    includes = ["/home/mboujema/.conan/data/fmt/8.0.1/_/_/package/20da98908a15523bbe9f086a5c57a4bde424a9c0/include"],
    
    
    
    visibility = ["//visibility:public"],
    
    deps = [
    
    ":fmtd_precompiled",
    
    ],
    
)
```

Everything seems to be equal but the `hdrs` key  should be a `glob` expression relative to the package path

**Comment by mohabouje** [comment]
Could be related: https://github.com/conan-io/conan/commit/26b2dbcc8c910c47cc42b197ed3ca04320127f3a#diff-5448f143013e48f4a5b8d403315532079730f5335ffba27c09a90e7e965bcd73

**Comment by memsharded** [comment]
Yes, this is not related to the previous (yesterday) error, but to another change that was done this release. Having a look.

**Comment by memsharded** [comment]
I am proposing this PR: https://github.com/conan-io/conan/pull/10478. There are several issues:

- Base ``cpp_info`` have moved to absolute paths, for other reasons, but the bazel ``glob`` needs them relative (fixed in the PR)
- The Bazel tests in the suite were flawed, they were actually not testing the dependency, but one single project code without dependencies, that made this issue not detected. The test has been quickly fixed, but it is clear that this integration needs more thorough and comprehensive functional tests.

**Comment by mohabouje** [comment]
This fix does not solve the issue:
```
conanfile.py (tijara-conan-integration/0.0.1): ERROR: Traceback (most recent call last):
  File "/home/mboujema/.local/lib/python3.9/site-packages/conans/client/generators/__init__.py", line 174, in write_generators
    generator.generate()
  File "/home/mboujema/.local/lib/python3.9/site-packages/conan/tools/google/bazeldeps.py", line 27, in generate
    content = self._get_dependency_buildfile_content(dependency)
  File "/home/mboujema/.local/lib/python3.9/site-packages/conan/tools/google/bazeldeps.py", line 109, in _get_dependency_buildfile_content
    headers.append('"{}/**"'.format(_relativize_path(path, package_folder)))
  File "/home/mboujema/.local/lib/python3.9/site-packages/conan/tools/google/bazeldeps.py", line 103, in _relativize_path
    assert p.startswith(base_path)
AssertionError

ERROR: Error in generator 'BazelDeps': 
```

After commenting the assertions, i'm running into another issue:

```
conanfile.py (tijara-conan-integration/0.0.1): ERROR: Traceback (most recent call last):
  File "/home/mboujema/.local/lib/python3.9/site-packages/conans/client/generators/__init__.py", line 174, in write_generators
    generator.generate()
  File "/home/mboujema/.local/lib/python3.9/site-packages/conan/tools/google/bazeldeps.py", line 27, in generate
    content = self._get_dependency_buildfile_content(dependency)
  File "/home/mboujema/.local/lib/python3.9/site-packages/conan/tools/google/bazeldeps.py", line 128, in _get_dependency_buildfile_content
    "libdir": cpp_info.libdirs[0],
IndexError: list index out of range

ERROR: Error in generator 'BazelDeps': list index out of range
```

**Comment by mohabouje** [comment]
Looks like for some packages, we have:

```
p= /usr/include/freetype2 base_path= /home/mboujema/.conan/data/xorg/system/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
```
assertions fails then:
```
        def _relativize_path(p, base_path):
            # TODO: Very fragile, to test more
            assert os.path.isabs(p), "{} is not absolute".format(p)
            assert p.startswith(base_path)

            return p[len(base_path):].replace("\\", "/").lstrip("/")
 ```

I'm guessing we need to remove the preffix only if its there

**Comment by memsharded** [comment]
Hi @mohabouje 

I see, those are system packages using resources from the system (a bit surprising to see ``freetype`` there, as there is a Conan package for it). But then, if we don't make it relative and leave the absolute path, the ``glob`` will complain anyway, won't it?

**Comment by mohabouje** [comment]
I havent test it but most likely to be an issue indeed. 

Probably there is a conan recipe trying to use freetype from the system package even tho I have it on my conanfile, any form to force this?

**Comment by memsharded** [comment]
I am creating a new ticket to track this (as the original "glob" issue + some improvements on the testing and BazelDeps closed this one, better narrow the scope of the fix).

I don't think we will manage to make it for 1.45, as it is about to be branched (today), but lets try to stabilize and improve the integration for 1.46

**Comment by mohabouje** [comment]
Another thing, it use to generate the packages in conandeps folder, and you could easily link all of them to bazel as explained here: https://docs.conan.io/en/latest/integrations/build_system/bazel.html

Not anymore the case, this looks like this latest change broke this somehow. Packages get generated in the root folder instead.

**Comment by mohabouje** [comment]
I will downgrade to 1.44.1 and wait for a proper fix then, version 1.45 implies some refactoring of my build files. Thanks for the help!

**Comment by memsharded** [comment]
>Another thing, it use to generate the packages in conandeps folder, and you could easily link all of them to bazel as explained here: https://docs.conan.io/en/latest/integrations/build_system/bazel.html

Yes, that was something incorrectly hardcoded. The integration shouldn't hardcode the ``conandeps`` folder. Instead, the projects can define in ``layout()`` method something like ``self.folders.generators = "conandeps"`` if they want. This has been fixed and the ``layout()`` applied to failing tests.

**Comment by mohabouje** [comment]
Thanks for that, I always wanted to generate that somewhere outside the repo

**Comment by memsharded** [comment]
Then the new ``conan install --output-folder`` in 1.45, together with the layout defined in the recipe, will be probably of interest

**Comment by mohabouje** [comment]
```
Error:/home/mboujema/Developer/tijara/conandeps/simdjson/BUILD.bazel:5:10: //conandeps/simdjson:simdjson_precompiled: invalid label '/home/mboujema/.conan/data/simdjson/1.0.2/_/_/package/958c3b440426d3de5c0972e7f507dbde401ac1a5/lib/libsimdjson.a' in attribute 'static_library' in 'cc_import' rule: invalid target name '/home/mboujema/.conan/data/simdjson/1.0.2/_/_/package/958c3b440426d3de5c0972e7f507dbde401ac1a5/lib/libsimdjson.a': target names may not start with '/'
```

Originally, 1.44:
```
cc_import(
    name = "fmtd_precompiled",
    static_library = "lib/libfmtd.a"
)
```
In 1.45:

```

cc_import(
    name = "fmtd_precompiled",
    static_library = "/home/mboujema/.conan/data/fmt/8.0.1/_/_/package/20da98908a15523bbe9f086a5c57a4bde424a9c0/lib/libfmtd.a"
)
```

Not sure if its gonna make it to 1.45 but this is missing on this fix, 1.45 is not working with bazel right now
