### ISSUE TITLE
[bug] Tool requirement build fails with `-pr:b=<profile>`, but succeeds with `-pr=<profile>`

### ISSUE THREAD

**Issue by connorsmacd** [conan-io/conan#12437]
### Environment Details

  * Operating System+version: macOS 12.6 (Intel)
  * Compiler+version: Apple clang version 14.0.0 (clang-1400.0.29.102)
  * Conan version: 1.53.0
  * Python version: 3.10.8

**NOTE: This issue does not seem to be macOS-specific (see "Additional Notes")**

### Steps to reproduce

- Create a `conanfile.txt` with `glib` as a tool requirement like so:

```
[tool_requires]
glib/2.74.1
```

- Create and install a profile for macOS called `Macos` like so:

```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=14.0
compiler.libcxx=libc++
build_type=Release
```

- Run `conan install conanfile.txt --build=glib` with `-pr=Macos`, observe that the build succeeds
- Run same `conan install` command, but replace `-pr=Macos` with `-pr:b=Macos`, observe that the build fails with the following output:

```
../src/meson.build:2070:2: ERROR: Dependency 'libpcre2-8' is required but not found.
```

### Logs

[`meson-log.txt` from failed build](https://github.com/conan-io/conan/files/9912956/meson-log.txt)
[Output of `conan install conanfile.txt -pr:b=Macos --build=glib` (failed build)](https://github.com/conan-io/conan/files/9913154/conan_install_two_profiles.txt)
[Output of `conan install conanfile.txt -pr=Macos --build=glib` (successful build)](https://github.com/conan-io/conan/files/9913145/conan_install_one_profile.txt)

### Additional notes

- **I do not believe this issue is specific to macOS -- I see the same issue on our Ubuntu CI builders with a different profile**.
- I can reproduce using any other profile as the host profile.
- So far, I have only been able to reproduce the issue with GLib as a tool requirement. I assumed this issue was not a bug in the recipe, ~~since my understanding is that `-pr=<profile>` should be equivalent to `-pr:b=<profile> -pr:h=<profile>`. I apologize if that assumption was incorrect.~~
- My current workaround is to install with `-pr=<profile>` first to put the binary in my cache. I can then run `conan install` with `-pr:b=<profile>` and `--build=missing` to avoid building the package again.

**Comment by memsharded** [comment]
Hi @connorsmacd 

I have a quick question, why are you adding ``glib`` as a ``tool_requires``? It is not a tool, but a library, so it should be added as a regular ``requires`` wouldn't it?

**Comment by connorsmacd** [comment]
> Hi @connorsmacd
> 
> I have a quick question, why are you adding `glib` as a `tool_requires`? It is not a tool, but a library, so it should be added as a regular `requires` wouldn't it?

Good question. I am working on getting GStreamer to cross-build. GStreamer needs `glib-mkenums` as part of the build process, which is supplied by GLib. There may be other scripts/executables supplied by GLib that are used for building -- I'm not certain. For this reason, it seemed appropriate to add `glib` as a `tool_requires`.

There are other packages that similarly serve both as a tool and a library. For example, `protobuf` can be added as a `tool_requires` in order to use `protoc` during the build process.

**Comment by memsharded** [comment]
Ok, thanks for the explanation, I was not aware of those scripts,  just please make sure about this:

https://docs.conan.io/en/latest/devtools/build_requires.html

> The tool requirement was formerly named “build requirement” and has been renamed to highlight that the usage of this kind of requirement must be for “tools” exclusively, not being valid for libraries to express a “private” require or other meanings.

And you don't include headers or link libraries from that requirement. A way to help to achieve this is making sure you always use the 2 profiles, "build" and "host" profiles, explicitly passing "build" one in the command line.


I think this is not a Conan issue per-se, but some issue with the current recipes in ConanCenter. If @prince-chrismc or @uilianries can have a quick look to check it, we could transfer it to ``conan-center-index`` repo.

**Comment by connorsmacd** [comment]
Re:

> I assumed this issue was not a bug in the recipe, since my understanding is that `-pr=<profile>` should be equivalent to `-pr:b=<profile> -pr:h=<profile>`

I am just trying to understand how this is **not** a bug in Conan itself. Regardless of the package, why would a tool requirement fail to build only when a build profile is specified explicitly. Both `conan install` cases are trying to build the exact same binary, as evidenced by the identical package IDs (`7321193805ea53e6ab97f76e7ff364ed3daa18dc`), yet one fails and the other doesn't. What could the recipe possibly be doing to behave differently in these two scenarios?

**Comment by memsharded** [comment]
> I am just trying to understand how this is not a bug in Conan itself. Regardless of the package, why would a tool requirement fail to build only when a build profile is specified explicitly. Both conan install cases are trying to build the exact same binary, as evidenced by the identical package IDs (7321193805ea53e6ab97f76e7ff364ed3daa18dc), yet one fails and the other doesn't. What could the recipe possibly be doing to behave differently in these two scenarios?


I am not sure what you mean. Defining ``--profile:build=xxx`` is a opt-in that activates a completely different behavior in how Conan manages tool-requires. The dependency graph itself might be different, as transitive requires of ``tool_requires`` will no longer conflict with transitive requires of regular ``requires``, because they will be in a different "context", the "build" context. How the "build" context propagate information to its consumers in "host" context is also different from how "host" requires propagate information. So, activating the "build" profile can indeed produce a different behavior in Conan, and some recipes that can work without it might fail activating it, if recipes are not updated accordingly.

It doesn't matter if the "build" profile is identical to the default one, or identical to the "host" profile either. Just by defining a ``--profile:build``, the mere existence of the argument is an opt-in to a new way of expanding the dependency graph into "build" and "host" different contexts. If this argument is not provided, all packages are always in the same "host" context.

**Comment by connorsmacd** [comment]
> > I am just trying to understand how this is not a bug in Conan itself. Regardless of the package, why would a tool requirement fail to build only when a build profile is specified explicitly. Both conan install cases are trying to build the exact same binary, as evidenced by the identical package IDs (7321193805ea53e6ab97f76e7ff364ed3daa18dc), yet one fails and the other doesn't. What could the recipe possibly be doing to behave differently in these two scenarios?
>
> I am not sure what you mean. Defining --profile:build=xxx is a opt-in that activates a completely different behavior in how Conan manages tool-requires. The dependency graph itself might be different, as transitive requires of tool_requires will no longer conflict with transitive requires of regular requires, because they will be in a different "context", the "build" context. How the "build" context propagate information to its consumers in "host" context is also different from how "host" requires propagate information. So, activating the "build" profile can indeed produce a different behavior in Conan, and some recipes that can work without it might fail activating it, if recipes are not updated accordingly.
>
> It doesn't matter if the "build" profile is identical to the default one, or identical to the "host" profile either. Just by defining a --profile:build, the mere existence of the argument is an opt-in to a new way of expanding the dependency graph into "build" and "host" different contexts. If this argument is not provided, all packages are always in the same "host" context.

That answers my question. I thought `-pr=<profile>` was merely shorthand for `-pr:b=<profile> -pr:h=<profile>`, but that's incorrect. Thank you for the clarification.

**Comment by memsharded** [comment]
> That answers my question. I thought -pr=<profile> was merely shorthand for -pr:b=<profile> -pr:h=<profile>, but that's incorrect. Thank you for the clarification.

No, that is part of the historical evolution, and how Conan since 1.0 needs to move forward to not break things:
- Initially, the build profile didn't exist at all, everything used just one profile, and ``os_build`` and ``arch_build`` to try to handle cross-compilation cases
- It was a limited approach to cross-compilation, so a new mechanism was designed, using the "build" and "host" contexts concept
- The current recipes and CLI cannot be broken, so the previously existing ``-pr=profile`` cannot change its meaning to define a new behavior, so the only way to introduce the new behavior is adding new arguments. The most consistent one in this case was the ``-pr:b``

**Comment by SpaceIm** [comment]
Looks like the same bug as https://github.com/conan-io/conan/issues/12375 & https://github.com/conan-io/conan-center-index/issues/13704, and likely a conan client issue, not a recipe issue (https://github.com/conan-io/conan/issues/12375#issuecomment-1288171548).

So basically the problem is that `CMakeDeps` & `PkgConfigDeps` don't generate files related to `requires` during build of a recipe when the build of this recipe is trigged while recipe is a tool_requires of another recipe, or a tool_requires of a profile.

Example:

`recipeA` in requires of `recipeB` (and build of `recipeB` relies on `PkgConfigDeps` to find & link to libs of `recipeA`).
`recipeB` in requires of a `conanfile_ok.txt`.
`recipeB` in tool_requires of `conanfile_ko.txt`.

Build of `recipeB` succeeds in this case:

```
conan install <path/to/conanfile_ok.txt> -b -pr:b default
```

Build of `recipeB` fails in this case (because `PkgConfigDeps` doesn't generate files of `recipeA` when `recipeB` is built):

```
conan install <path/to/conanfile_ko.txt> -b -pr:b default
```

**Comment by ericLemanissier** [comment]
friendly ping @memsharded do you need more information to investigate the situation described by @SpaceIm in the message above ?

**Comment by paulharris** [comment]
I hit this bug on Windows with vs17, trying to build harfbuzz.
I got the message:
```
Configuring harfbuzz-config.cmake using configuration
Program glib-mkenums mkenums found: NO
..\src\src\meson.build:684:2: ERROR: Program 'glib-mkenums mkenums' not found or not executable
```

When I used both -pr:b and -pr:h.
Seems to work ok with just -pr

**Comment by ericLemanissier** [comment]
see also https://github.com/conan-io/conan-center-index/issues/14125

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/conan/pull/12712 for 1.56

**Comment by larshg** [comment]
> I hit this bug on Windows with vs17, trying to build harfbuzz. I got the message:
> 
> ```
> Configuring harfbuzz-config.cmake using configuration
> Program glib-mkenums mkenums found: NO
> ..\src\src\meson.build:684:2: ERROR: Program 'glib-mkenums mkenums' not found or not executable
> ```
> 
> When I used both -pr:b and -pr:h. Seems to work ok with just -pr

I'm still experiencing this, even after installing conan 1.56.
Should I open a new issue, since the most of them linked to this primarily refers to the libpcre2-8 dependency problem?

**Comment by memsharded** [comment]
Hi @larshg 

Yes, please submit a new issue, it is easier to track than a closed one.
If possible, add reproducible instructions with simple conan recipes, no full recipes from ConanCenter, as those are way harder to debug, and it could be recipe issues too (but of course not a problem, if this is the only way to reproduce, just whenever possible). Thanks!
