### ISSUE TITLE
[bug] validate_build fails to report errors when building "self" or "root" node

### ISSUE THREAD

**Issue by System-Arch** [conan-io/conan#12571]
### Environment Details (include every applicable attribute)
  * Operating System+version: Debian 10
  * Compiler+version: gcc 8
  * Conan version: 2.0-beta5
  * Python version: 3.7.3

### Steps to reproduce (Include if Applicable)

> conan-2.0 build --name vb --version 1.0 -o "vb/*:my_option=False" .

### Logs (Executed commands with output) (Include/Attach if Applicable)

> -------- Input profiles --------
> Profile host:
> [settings]
> arch=x86_64
> build_type=Release
> compiler=gcc
> compiler.cppstd=gnu14
> compiler.libcxx=libstdc++11
> compiler.version=8
> os=Linux
> [options]
> vb/*:my_option=False
> 
> Profile build:
> [settings]
> arch=x86_64
> build_type=Release
> compiler=gcc
> compiler.cppstd=gnu14
> compiler.libcxx=libstdc++11
> compiler.version=8
> os=Linux
> 
> 
> -------- Computing dependency graph --------
> Graph root
>     conanfile.py (vb/1.0): /tmp/vb/conanfile.py
> 
> -------- Computing necessary packages --------
> *********** validate_build detected invalid configurration *************
> 
> -------- Installing packages --------
> 
> -------- Installing (downloading, building) binaries... --------
> 
> -------- Finalizing install (deploy, generators) --------
> conanfile.py (vb/1.0): Aggregating env generators
> conanfile.py (vb/1.0): Calling build()
> Building vb

Here's the associated conanfile.py:

from conan import ConanFile
from conan.errors import ConanInvalidConfiguration

class vbConan(ConanFile):
    name = "vb"
    version = "1.0"
    options = {"my_option": [True, False]}
    default_options = {"my_option": True}

    def validate_build(self):
        if not self.options.my_option:
            print("*********** validate_build detected invalid configurration *************")
            raise ConanInvalidConfiguration("This doesn't build with False option")

    def build(self):
        print("Building vb")

**Comment by System-Arch** [comment]
From what I can tell, validate_build() errors are only being reported for dependencies of the current target and not on that target itself. This assumption is based on the logic found in: conans/client/graph/install_graph.py:

>     def raise_errors(self):
>         missing, invalid = [], []
>         for ref, install_node in self._nodes.items():
>             for package in install_node.packages.values():
>                 if package.binary == BINARY_MISSING:
>                     missing.append(package)
>                 elif package.binary in (BINARY_INVALID, BINARY_ERROR):
>                     invalid.append(package)
> 
>         if invalid:
>             msg = ["There are invalid packages (packages that cannot exist for this configuration):"]
>             for package in invalid:
>                 node = package.nodes[0]
>                 if node.cant_build:
>                     binary, reason = "Cannot build for this configuration", node.cant_build
>                 else:
>                     binary, reason = node.conanfile.info.invalid
>                 msg.append("{}: {}: {}".format(node.conanfile, binary, reason))
>             raise ConanInvalidConfiguration("\n".join(msg))
>         if missing:
>             self._raise_missing(missing)

I believe this logic skips the "self" (target) or "root" node in the graph and thus the errors associated with this node go unreported.

**Comment by memsharded** [comment]
Thanks for the detailed report and the investigation.
The check for the current "consumer" happens in a different place, because it is not a package yet. I am proposing a potential fix in https://github.com/conan-io/conan/pull/12573

**Comment by System-Arch** [comment]
Hi @memsharded,
Thank you for the quick resolution . I tested the fix and it indeed addresses my original use case.

**Comment by memsharded** [comment]
Great, many thanks for testing it!

**Comment by System-Arch** [comment]
Hi @memsharded,
One more question--will this fix be backported to Conan 1.x as it seems to exhibit the same issue? Thanks

**Comment by memsharded** [comment]
> One more question--will this fix be backported to Conan 1.x as it seems to exhibit the same issue? Thanks

I don't think so, because we discussed about this, and even if a bit weird, it could be breaking, as some users using the local flow could be working for them (forcing a mismatch from declared settings), and they would like the ``validate()`` only to avoid building in the cache. So the risk of breaking them is not worth it.

**Comment by System-Arch** [comment]
Hi @memsharded,

Interesting, This complicates the compatibility strategy that CCI is using. On a related note, do you know if there are plans to permit access to self.options (in addition to self.info.options) in the validate() method in 2.0 or 1.x? Thanks

**Comment by memsharded** [comment]
> Interesting, This complicates the compatibility strategy that CCI is using.

It shouldn't. CCI works on ``export``ed recipes in the cache, in that case the ``validate_build()`` should still work, the issue fixed here is for the local flow only, but CCI is not using it.


> Interesting, This complicates the compatibility strategy that CCI is using. On a related note, do you know if there are plans to permit access to self.options (in addition to self.info.options) in the validate() method in 2.0 or 1.x? Thanks

Yes, this has been fixed already in the ``develop2`` branch, it will be reverted, and the recommended approach will be to use ``self.settings`` and ``self.options`` in both ``validate/validate_build()`` methods, in both 1.X and 2.0.

**Comment by System-Arch** [comment]
Hi @memsharded,

> It shouldn't. CCI works on exported recipes in the cache, in that case the validate_build() should still work, the issue fixed here is for the local flow only, but CCI is not using it.

What I meant here was use of the CCI recipes in green field projects.

> Yes, this has been fixed already in the develop2 branch, it will be reverted, and the recommended approach will be to use self.settings and self.options in both validate/validate_build() methods, in both 1.X and 2.0.

Will self.info.* still exist and are they essentially outputs from the recipe's point of view and only used for matching package ID's? Just trying to get a clear picture of the model in my head.

Thanks

**Comment by memsharded** [comment]
> What I meant here was use of the CCI recipes in green field projects.

Yes, CCI recipes that are used with the local flow will not raise in 1.X. But that shouldn't be a huge use case, compared with others, as third-party dependencies are not that typically to be developed with the local flow. Most of the users just do a ``conan create`` + ``conan upload`` in CI to populate the third party packages.

> Will self.info.* still exist and are they essentially outputs from the recipe's point of view and only used for matching package ID's? Just trying to get a clear picture of the model in my head.

Yes, ``self.info`` still exists in 2.0, and its main, probably unique usage, will be for ``package_id()`` binary compatibility custom definition. And maybe many of the cases for binary compatibility will shift to an external ``compatibility.py`` plugin that will live in the Conan cache.
