### ISSUE TITLE
[bug] Bazel generator ignores binaries/executables in a package

### ISSUE THREAD

**Issue by a4z** [conan-io/conan#13197]
### Environment details

* Operating System+version: Any
* Compiler+version: Any 
* Conan version: 1.59, very likely all others also
* Python version: Any

### Steps to reproduce

When using protobuf, for example, the generated BUILD file looks like followed:

```
load("@rules_cc//cc:defs.bzl", "cc_import", "cc_library")

cc_import(
    name = "protoc_precompiled",
    static_library = "lib/libprotoc.a",
)

cc_import(
    name = "protobuf_precompiled",
    static_library = "lib/libprotobuf.a",
)

cc_library(
    name = "protobuf",
    hdrs = glob(["include/**"]),
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        # do not sort
        ":protoc_precompiled",
        ":protobuf_precompiled",
    ],
)
```

That is correct for the static library part. 
But protobuf also comes with a binary, `protoc` , and this file is lost. 

Maybe there should be at least a bazel `filegroup`, exposing the binary (binaries)

```
filegroup(
    name = "protoc",
    srcs = ["bin/protoc"],
    visibility = ["//visibility:public"],
)
```

for the binary can be accessed, and a user can make their `sh_binary` wrapper or whatever in bazel

---
This is, btw, also missing for dynamic libraries, which also needs to be put in place by bazel. I needed to patch every generated BUILD file to add that, so just for the few exceptions I have with dynamic libraries,  there is a file group and user can care about that they get placed on the right location fir executables to find them. 
But that should possible be an extra issue? Nor sure, its very related

**Comment by franramirez688** [comment]
Hi @a4z 

Thanks for reporting it.

It should be solved by https://github.com/conan-io/conan/pull/14959

Now, BazelDeps adds to each BUILD file something like this:
```
# Filegroup library declaration
filegroup(
    name = "glew_binaries",
    srcs = glob([
        "bin/**",
    ]),
    visibility = ["//visibility:public"],
)
```

**Comment by a4z** [comment]
Awesome, good to see that the existing Conan 1 users still get some love !

Thank you!

**Comment by franramirez688** [comment]
Closed by https://github.com/conan-io/conan/pull/14959

It'll be released in the next Conan v1.62.
