### ISSUE TITLE
[bug] An error occurred during the installation process.

### ISSUE THREAD

**Issue by Entity-Now** [conan-io/conan#13644]
### Environment details

* Operating System+version: windows 10 22H2
* Compiler+version: Visual Studio 17 2022
* Conan version: 2.3
* Python version: none
```conanfile
[requires]
    boost/1.81.0
[generators]
    CMakeDeps
    CMakeToolchain
```

### Steps to reproduce

mkdir build
cd build 
conan profile detect --force
conan install . --output-folder=build --build=missing

### Logs

```
======== Finalizing install (deploy, generators) ========
conanfile.txt: Writing generators to E:\c++\ConanTwoTest\build
conanfile.txt: Generator 'CMakeDeps' calling 'generate()'
conanfile.txt: ERROR: Traceback (most recent call last):
  File "conan\tools\cmake\cmakedeps\templates\__init__.py", line 42, in render
  File "conan\tools\cmake\cmakedeps\templates\target_data.py", line 54, in context
  File "ntpath.py", line 643, in commonpath
ValueError: Paths don't have the same drive
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "conans\client\generators\__init__.py", line 70, in write_generators
  File "conan\tools\cmake\cmakedeps\cmakedeps.py", line 42, in generate
  File "conan\tools\cmake\cmakedeps\cmakedeps.py", line 84, in content
  File "conan\tools\cmake\cmakedeps\cmakedeps.py", line 97, in _generate_files
  File "conan\tools\cmake\cmakedeps\templates\__init__.py", line 44, in render
conans.errors.ConanException: error generating context for 'boost/1.81.0': Paths don't have the same drive

ERROR: Error in generator 'CMakeDeps': error generating context for 'boost/1.81.0': Paths don't have the same drive
```

**Comment by Entity-Now** [comment]
Additional content
```text
boost/1.81.0: Package '3becda85e285acf424c7e0743f5974d5b1669ddc' built
boost/1.81.0: Build folder C:\Users\Administrator\.conan2\p\t\boost900e52042ea7c\b\build-release
boost/1.81.0: Generating the package
boost/1.81.0: Temporary package folder C:\Users\Administrator\.conan2\p\t\boost900e52042ea7c\p
boost/1.81.0: Calling package()
boost/1.81.0: package(): Packaged 14939 '.hpp' files
boost/1.81.0: package(): Packaged 148 '.h' files
boost/1.81.0: package(): Packaged 341 '.ipp' files
boost/1.81.0: package(): Packaged 17 files
boost/1.81.0: package(): Packaged 2 '.inc' files: cpp_re.inc, strict_cpp_re.inc
boost/1.81.0: package(): Packaged 41 '.lib' files
boost/1.81.0: package(): Packaged 1 '.txt' file: LICENSE_1_0.txt
boost/1.81.0: Created package revision 4dceafdc6f1e41b3b686af6195343c5e
boost/1.81.0: Package '3becda85e285acf424c7e0743f5974d5b1669ddc' created
boost/1.81.0: Full package reference: boost/1.81.0#8dcd9d9df9e0d320714b83cceddbe120:3becda85e285acf424c7e0743f5974d5b1669ddc#4dceafdc6f1e41b3b686af6195343c5e
boost/1.81.0: Package folder C:\Users\Administrator\.conan2\p\boost6e9f3f14ffd62\p
boost/1.81.0: Disabled magic autolinking (smart and magic decisions)
WARN: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN:     'env_info' used in: bzip2/1.0.8, b2/4.9.3, boost/1.81.0
WARN:     'cpp_info.names' used in: bzip2/1.0.8, boost/1.81.0, zlib/1.2.13
WARN:     'cpp_info.build_modules' used in: bzip2/1.0.8
WARN:     'cpp_info.filenames' used in: boost/1.81.0
WARN:     'user_info' used in: boost/1.81.0

======== Finalizing install (deploy, generators) ========
conanfile.txt: Writing generators to E:\c++\ConanTwoTest\build
conanfile.txt: Generator 'CMakeToolchain' calling 'generate()'
conanfile.txt: CMakeToolchain generated: conan_toolchain.cmake
conanfile.txt: Preset 'conan-default' added to CMakePresets.json. Invoke it manually using 'cmake --preset conan-default' if using CMake>=3.23
conanfile.txt: If your CMake version is not compatible with CMakePresets (<3.23) call cmake like: 'cmake <path> -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=E:\c++\ConanTwoTest\build\conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW'
conanfile.txt: CMakeToolchain generated: CMakePresets.json
conanfile.txt: CMakeToolchain generated: ..\CMakeUserPresets.json
conanfile.txt: Generator 'CMakeDeps' calling 'generate()'
conanfile.txt: ERROR: Traceback (most recent call last):
  File "conan\tools\cmake\cmakedeps\templates\__init__.py", line 42, in render
  File "conan\tools\cmake\cmakedeps\templates\target_data.py", line 54, in context
  File "ntpath.py", line 643, in commonpath
ValueError: Paths don't have the same drive

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "conans\client\generators\__init__.py", line 70, in write_generators
  File "conan\tools\cmake\cmakedeps\cmakedeps.py", line 42, in generate
  File "conan\tools\cmake\cmakedeps\cmakedeps.py", line 84, in content
  File "conan\tools\cmake\cmakedeps\cmakedeps.py", line 97, in _generate_files
  File "conan\tools\cmake\cmakedeps\templates\__init__.py", line 44, in render
conans.errors.ConanException: error generating context for 'boost/1.81.0': Paths don't have the same drive

ERROR: Error in generator 'CMakeDeps': error generating context for 'boost/1.81.0': Paths don't have the same drive
```

**Comment by memsharded** [comment]
Hi @Entity-Now 

Thanks for reporting this.
There was a regression in 2.0.3, that our test suite was not covering (it is not easy to test using different drives in our Windows CI).
This has been fixed already in https://github.com/conan-io/conan/pull/13607 and will be released in next 2.0.4 soon (hopefully end of next week).

**Comment by damian123** [comment]
@marache  This bug is still there in the newest source code in GitHub, is there another pr that solves this?

**Comment by memsharded** [comment]
If you want to test from source, please checkout the branch ``release/2.0``, that is the reference branch for next 2.0.4 release. Is this the branch that you are testing?

**Comment by memsharded** [comment]
We will be releasing 2.0.4 shortly (today or tomorrow), this was closed by https://github.com/conan-io/conan/pull/13607, so closing the issue. Please re-open if necessary after updating to 2.0.4, thanks!
