### ISSUE TITLE
[bug] Save and restore packages from the cache failing when saving in windows and restoring in unix

### ISSUE THREAD

**Issue by obajj-dlb** [conan-io/conan#15252]
### Environment details

Save side:
* Operating System+version: Windows 10
* Compiler+version: Visual Studio 16 2019 (MSVC 19.2)
* Conan version: 2.0.14
* Python version: 3.10.11

Restore side:
* Operating System+version: macos ventura 13.6.1 (22G313)
* Compiler+version: Apple clang version 15.0.0
* Conan version: 2.0.14
* Python version: 3.11.6

### Steps to reproduce

1. Create a package in windows. I've tried to create different packages with different libraries
2. Try to export using the conan cache restore command in a windows environment

Exporting the same package in linux or antoher mac device is not failing. 
I don't know if doing this process the opposite way (save in windows and export in unix does fail)

### Logs

-> % conan cache restore windows-x86_64.tgz
				ERROR: Traceback (most recent call last):
				  File "/usr/local/Cellar/conan/2.0.14/libexec/lib/python3.12/site-packages/conan/cli/cli.py", line 272, in main
				    cli.run(args)
				  File "/usr/local/Cellar/conan/2.0.14/libexec/lib/python3.12/site-packages/conan/cli/cli.py", line 172, in run
				    command.run(self._conan_api, args[0][1:])
				  File "/usr/local/Cellar/conan/2.0.14/libexec/lib/python3.12/site-packages/conan/cli/command.py", line 141, in run
				    sub.run(conan_api, parser, *args)
				  File "/usr/local/Cellar/conan/2.0.14/libexec/lib/python3.12/site-packages/conan/cli/command.py", line 155, in run
				    info = self._method(conan_api, parent_parser, self._parser, *args)
				           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
				  File "/usr/local/Cellar/conan/2.0.14/libexec/lib/python3.12/site-packages/conan/cli/commands/cache.py", line 146, in cache_restore
				    package_list = conan_api.cache.restore(path)
				                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
				  File "/usr/local/Cellar/conan/2.0.14/libexec/lib/python3.12/site-packages/conan/api/subapi/cache.py", line 162, in restore
				    assert rel_path == recipe_folder, f"{rel_path}!={recipe_folder}"
				AssertionError: p/utilicc39abe1a64b1!=p\utilicc39abe1a64b1
 
				ERROR: p/utilicc39abe1a64b1!=p\utilicc39abe1a64b1

**Comment by memsharded** [comment]
Hi @obajj 

Thanks for reporting this.

It seems that some Windows backslash paths have slipped into the manifests, which are wrong in other platforms (most likely the other way round it works), so this seems indeed a bug.

We'll try to fix it asap.

**Comment by memsharded** [comment]
Fixed by https://github.com/conan-io/conan/pull/15253 for next 2.0.15

**Comment by obajj** [comment]
Hi @memsharded 
I am trying to run the same commands and it looks like it is still failling, but slightly different:
    AssertionError: p/utilie2f85956fb77e!=ptilie2f85956fb77e
Do you know what can it be? Should I open another issue?

**Comment by obajj-dlb** [comment]
Hi @memsharded ,
I've been trying to restore a windows package in a linux environment and it is still failling:
    ERROR: p/utilie2f85956fb77e!=ptilie2f85956fb77e
I'm using the same commands described above and conan 2.0.16

Should I open another issue?

**Comment by memsharded** [comment]
Yes, please open a new ticket for this.
Take into account that previously saved packages won't be able to work, you need to re-capture them, that will force them having "/" slash.
