### ISSUE TITLE
Can not connect to conan.io due to SSL certification mismatch hostname

### ISSUE THREAD

**Issue by canmor** [conan-io/conan#2649]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

---

Here's my environments:

* OS: macOS High Sierra  10.13.3
* shell: zsh 5.3
* Conan version: 1.1.1

Steps to reproduce:

1. Install conan over Homebrew:

```shell
$ brew install conan
```

2. Follow official guide to clone `example-poco-timer.git`

```shell
$ git clone https://github.com/memsharded/example-poco-timer.git mytimer
```

3. Enter project and run install:

```shell
$ conan install .
```

Then error comes:

```
Poco/1.8.0.1@pocoproject/stable: Not found in local cache, looking in remotes...
Poco/1.8.0.1@pocoproject/stable: Trying with 'conan.io'...
ERROR: HTTPSConnectionPool(host='server.conan.io', port=443): Max retries exceeded with url: /v1/conans/Poco/1.8.0.1/pocoproject/stable/download_urls (Caused by SSLError(CertificateError("hostname 'server.conan.io' doesn't match either of '*.bintray.com', 'bintray.com'",),))

Unable to connect to conan.io=https://server.conan.io
```

Seams `server.conan.io` is alias to `bintray.com` but SSL certification is for `bintray.com` only, don't match to hostname `server.conan.io`, how to workaround this?

**Comment by danimtb** [comment]
Seems that you were comming from an old installation of conan and it is using the old configuration as `server.conan.io` was moved to Bintray.

I you dont have any important configuration in the conan folder or valuable package in the cache, I suggests deletetin the _~/.conan_ folder and run conan again to regenerate the config files.

**Comment by memsharded** [comment]
I'd also recommend try running a ``pip install conan --upgrade``, to make sure the dependencies are updated too, in case you had old versions from a previous old installation of conan.

**Comment by canmor** [comment]
@danimtb Thanks for your solution, problem get solved by `rm -rf ~/.conan`. Seams I'd installed conan 0.1 by pip long time ago on my Mac, and install the latest version by Homebrew now.

@memsharded Didn't get a change to try your solution, but much appreciate for your suggestion.

**Comment by ruimaciel** [comment]
I've just installed conan v1.5.2 from the official Debian/Ubuntu package and I'm experiencing the exact same problem.

Deleting ~/.conan doesn't solve this problem.

Here's the output after deleting the folder:

```
rm@debian:~/development/mytimer/build$ conan install ..
Auto detecting your dev setup to initialize the default profile (/home/rm/.conan/profiles/default)
Found gcc 6.3
gcc>=5, using the major as version
Found clang 3.8

************************* WARNING: GCC OLD ABI COMPATIBILITY ***********************
 
Conan detected a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
'libstdc++' for backwards compatibility.
Your compiler is likely using the new CXX11 ABI by default (libstdc++11).

If you want Conan to use the new ABI, edit the default profile at:

    ~/.conan/profiles/default

adjusting 'compiler.libcxx=libstdc++11'

************************************************************************************



Default settings
        os=Linux
        os_build=Linux
        arch=x86_64
        arch_build=x86_64
        compiler=gcc
        compiler.version=6
        compiler.libcxx=libstdc++
        build_type=Release
*** You can change them in /home/rm/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***


WARN: Remotes registry file missing, creating default one in /home/rm/.conan/registry.txt
Poco/1.8.0.1@pocoproject/stable: Not found in local cache, looking in remotes...
Poco/1.8.0.1@pocoproject/stable: Trying with 'conan-center'...
ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/conans/Poco/1.8.0.1/pocoproject/stable/download_urls (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))

Unable to connect to conan-center=https://conan.bintray.com
```

**Comment by memsharded** [comment]
Hi @ruimaciel 

It seems it could be an issue of the pyinstaller (the program that generates the standalone conan app to be distributed in the installers). Could you please check with the ``pip`` installed version in the same machine to see if it works?

This PR https://github.com/conan-io/conan/pull/3036 just merged in "develop" branch might help. In the meantime:

- Could you please tell which is your distro and version?
- Is it a regression, do the previous installers from previous versions work correctly in the same machine?

Thanks!

**Comment by ruimaciel** [comment]
@memsharded I've checked the pip installed version in the same machine and it works.

I've tested the deb package in Debian's current stable release (Debian 9.4).

**Comment by memsharded** [comment]
Thanks for telling @ruimaciel 
So please keep tuned to the conan 1.6 release, as that PR might solve the issue. Or if it is critical and you wanted to make sure it will work, it would be great if you could help us testing it. What you would need:

- Clone the conan repo sources
- Move to the branch with the changes in #3036
- Launch the pyinstaller.py file that is in the conan repo root
- Use the generated binary by pyinstaller, and test if it works

I know this is not a simple thing, so I understand if you can't do it, and please do not hesitate to ask for help if needed. Thanks!

**Comment by ruimaciel** [comment]
Hi @memsharded 

I was just trying out conan, and unfortunately the official version installed from the official package was broken.  Not a good first experience, I might say.

 I've followed your test procedure with commit 9e0be24a57551a in a virtual environment and, although I was able to generate the binary, the binary failed to run.  I've stumbled on a problem that sounds very similar to the one reported in here.

https://stackoverflow.com/questions/49391453/pyinstaller-cannot-open-shared-object-libpython3-5m-so-1-0

**Comment by memsharded** [comment]
HI @ruimaciel 

Sorry, could you please clarify? Above you said:

> @memsharded I've checked the pip installed version in the same machine and it works.

Then:

> I was just trying out conan, and unfortunately the official version installed from the official package was broken.

You meant the .deb installer, right?

The thing is that generating the installers uses pyinstaller, and the way that it bundles the application is outside of our control. This is the reason we strongly recommend the pip installed, if you check the docs:

> The preferred and strongly recommended way to install Conan is from PyPI, the Python Package Index, using the pip command.
There are other available installers for different systems, which might come with a bundled python interpreter, so that you don’t have to install python first. Please note that some of these installers might have some limitations, specially those created with pyinstaller (such as Windows exe & Linux deb).

Also explicitly in the downloads page https://conan.io/downloads:

> (MAY HAVE LIMITATIONS, PLEASE USE THE PYPI INSTALLER IF POSSIBLE)

We are willing to ease the onboarding on conan as much as possible, and this is the reason we make an extra effort to create and distribute those installers too. But it is a very challenging task, specially when they are created with tools like pyinstaller that we don't control, and it is impossible that they will work for 100% of cases, and this is why the help and support of the community is needed to debug and improve them. Thanks very much for reporting, I am going to re-open to try to investigate and fix it if possible.

**Comment by lasote** [comment]
Starting from 1.6 we are going to distribute the `deb` installer with all the shared libraries that the pyinstaller is "capturing". I tried with debian 9 and it works perfectly.
