### ISSUE TITLE
[bug] Linter "Unable to import" warning when importing a shared Python Conan package in the build() step

### ISSUE THREAD

**Issue by smokris** [conan-io/conan#2692]
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

---

I followed the instructions on http://docs.conan.io/en/latest/howtos/python_code_reuse.html.  When I get to the "Requiring a python conan package" step, the linter gives me a warning about importing the shared package:

    $ git clone https://github.com/smokris/conan-test-library
    $ cd conan-test-library
    $ conan export . me/testing
    $ cd ..

    $ git clone https://github.com/smokris/conan-test-consumer
    $ cd conan-test-consumer
    $ conan create . me/testing
    HelloPyReuse/1.0@me/testing: Exporting package recipe
    Linter warnings
        WARN: Linter. Line 9: Unable to import 'hello'
    …
    HelloPyReuse/1.0@me/testing: Calling build()
    Hello World from Python!
    …

(The imported package works fine; the problem is just that the linter is emitting a warning.  I'd prefer that the linter not show this false-positive warning, to improve the linter's signal-to-noise ratio.)

I'm able to reproduce this using:

- Conan 1.1.1 on my local macOS 10.13.3 system
- Conan 1.1.1 on Travis CI's Mac OS 10.10.5 image
- Conan 1.1.1 on Travis CI's Ubuntu 14.04.5 image
- Conan 1.2.0 on CentOS 7.4

**Comment by lasote** [comment]
Thanks for reporting. Could you confirm the issue in Conan 1.2? We released it today.

**Comment by smokris** [comment]
> Could you confirm the issue in Conan 1.2? We released it today.

Oh, thanks, I hadn't seen that it was released already.

I just tested with Conan 1.2.0 on CentOS 7.4, but I'm still seeing the linter warning described above.
