### ISSUE TITLE
Zlib bintray problems

### ISSUE THREAD

**Issue by liberforce** [conan-io/conan#3729]
Sorry, I don't really know where to report conan+bintray problems. Please tell me the right location if it's not here.

```
$ conan search -r conan-center zlib
ERROR: {"message":"Oops. Looks like you've reached a dark spot."}. [Remote: conan-center]

```

This breaks my builds:

```
zlib/1.2.11@conan/stable: Not found in local cache, looking in remotes...
zlib/1.2.11@conan/stable: Trying with 'conan-center'...
ERROR: Failed requirement 'zlib/1.2.11@conan/stable' from 'boost/1.64.0@sbre/testing'
ERROR: {"message":"Oops. Looks like you've reached a dark spot."}. [Remote: conan-center]
ERROR: Job failed: exit status 1
```

The same kind of problem already happened with bzip2 las summer...

Using conan 1.8.0 both on Windows 2016 server and Ubuntu 14.04.

To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by liberforce** [comment]
I think having a message pointing to https://status.bintray.com would be better than the puzzling
"Oops. Looks like you've reached a dark spot."...

**Comment by lasote** [comment]
The issue should be fixed now. Please comment if it doesn't

**Comment by uilianries** [comment]
Its not working ...

```
$ conan search zlib/1.2.11@conan/stable -r conan-center
ERROR: Unable to retrieve resource.. [Remote: conan-center]
```

but

```
$ conan search zlib/1.2.11@conan/testing -r conan-center
Existing packages for recipe zlib/1.2.11@conan/testing:

Existing recipe in remote 'conan-center':

    Package_ID: 014be746b283391f79d11e4e8af3154344b58223
        [options]
            shared: False
        [settings]
            arch: x86_64
            build_type: Debug
            compiler: gcc
            compiler.exception: seh
            compiler.threads: posix
            compiler.version: 5
...
```

```
$ conan remote list
bincrafters: http://api.bintray.com/conan/bincrafters/public-conan [Verify SSL: True]
conan-center: https://conan.bintray.com [Verify SSL: True]
conan-community: https://api.bintray.com/conan/conan-community/conan [Verify SSL: True]
```

it looks like I can reach testing but not stable channel.

I'm running Conan 1.8.2

**Comment by liberforce** [comment]
I confirm this is not fixed, only the error message changed. Please Reopen.

**Comment by lasote** [comment]
Working here, could someone confirm that the error is still happening?

**Comment by liberforce** [comment]
@lasote : Right, it's working now. Thanks.

@Croydon : Your poblem looks unrelated, you should file a separaet issue.

**Comment by liberforce** [comment]
@uilianries : Argh, you're right, I somehow used the wrong command. zlib/1.2.11@conan/**testing** works, but not zlib/1.2.11@conan/**stable**.

```
$ conan search zlib/1.2.11@conan/stable -r conan-center
ERROR: Unable to retrieve resource.. [Remote: conan-center]

```
So there's still a bug.

**Comment by danimtb** [comment]
Solved issue with the Bintray team. It is working now!

**Comment by uilianries** [comment]
@danimtb Thanks!

**Comment by d70-t** [comment]
It seems like I am still having a similar or the same problem. This command (copied from the docs https://docs.conan.io/en/latest/reference/commands/consumer/search.html ) fails:

    $ conan search zlib/* -r conan-center
    ERROR: {"message":"Oops. Looks like you've reached a dark spot."}. [Remote: conan-center]

and also:

    $ conan search zlib/1.2.11@conan/stable -r conan-center
    ERROR: Unable to retrieve resource.. [Remote: conan-center]

as well as:

    $ conan search zlib/1.2.11@conan/testing -r conan-center
    ERROR: Recipe not found: conan/zlib/1.2.11/testing. [Remote: conan-center]

I can reproduce this behavior with my regular install as well as inside the docker container `conanio/gcc72`.

@danimtb If I am missing the solution you are referring to, can you give me a hint where to find it? Thanks.

**Comment by liberforce** [comment]
@d70-t : the problem is server-side (Bintray repository), so there's no solution you can find on the client-side (conan).

**Comment by liberforce** [comment]
I can confirm there's an issue again. Could this bug be reopened? I am the reporter but can't find a way to reopen.

**Comment by uilianries** [comment]
Hi!

Yes, I can confirm the same error:

    $ conan search zlib/* -r conan-center
       ERROR: {"message":"Oops. Looks like you've reached a dark spot."}. [Remote: conan-center]
    $ conan search zlib/1.2.11@conan/stable -r conan-center
      ERROR: Unable to retrieve resource.. [Remote: conan-center]

**Comment by danimtb** [comment]
Yes, we reported the issue yesterday to the bintray team.
The search is failing whereas the install command still work.

Reopening the issue. Thanks for reporting!

**Comment by danimtb** [comment]
The search of `zlib` is back working fine for all the versions. I have also performed downloads of all packages and they are installing right.

```
$ conan download zlib/1.2.11@conan/stable -r conan-center
...
$ conan download zlib/1.2.9@conan/stable -r conan-center
...
$ conan download zlib/1.2.8@conan/stable -r conan-center
...
```

Closing the issue as solved but please comment again of reopen if you find any trouble. Thanks!

**Comment by cjdb** [comment]
I've run into this problem when I add `"zlib/1.2.9@conan/stable"` to my list of dependencies.
