### ISSUE TITLE
Link order change

### ISSUE THREAD

**Issue by jallenwork** [conan-io/conan#4931]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I have a build system running on Linux currently using conan 1.11.2. I'm using `requires` to list public dependencies and `build_requires` for tooling dependencies and "private" dependencies i.e. tests with dependencies and the like. While working on an upgrade to conan 1.13.0 I encountered a change in behavior in the the link order produced in this setup. I'm curious if this is intended behavior and I'm perhaps misusing `build_requires` or if this is actually a bug?  

I have a 3 library deep dependency graph:  
`grass` <- `gazelle` <- `cheetah`  
The conanfile.py for cheetah has the following 2 lines:
```
requires = "gazelle/[*]@user/testing"
build_requires = "gtest/[*]@build/prod", "grass/[*]@user/testing"
```
The reason for the `build_requires` on grass is that one of the build time tests in this conan project has an explicit dependency on `grass`. 

In conan 1.11.2 and previous this all built and linked fine, but as of 1.13.0 (I didn't test on anything else between the two) the link order that conan generates from this conanfile chain is different and will no longer link. (It looks to me like `build_requires` is getting higher priority in the linker order now?)

I've assembled a simple reproducer at: https://github.com/jallenwork/LinkOrderOddness  
using the above naming scheme for clarity.

Thanks in advance for any assistance you can offer.

**Comment by memsharded** [comment]
Hi @jallenwork 

We are investigating this issue. I have been able to reproduce it with your repo, thanks very much for the effort in creating it, really useful.

Some things were indeed changed in Conan 1.13, in order to solve a couple of bugs related to build-requires not conflicting with regular requires when they should. It is possible that your project is affected by these changes. We keep investigating, it, but in the mean time, could you please clarify this:

- It is possible that you might be abusing some build-requires capability. In the same line of thought cheetah->gazelle (I like your example :) ), it might not make a lot of sense that cheetah has a build-require to grass. Could you please clarify and put real tool examples? Like using gtest, one library, cmake, etc. The reason is that it is a very unusual pattern to have a package both as a transitive requirement (grass<-gazelle) and as a build requirement. If it is a transitive requirement, it is already there, you don't need to "build-require" it. Maybe understanding the use case with real tool names, could help us understand. Thanks!

**Comment by jallenwork** [comment]
Thanks for the quick turnaround, and thanks for all your work on a great tool! :-D
I'll try to describe the situation:
`grass` in our example is a low level first party utility library(think of it like boost if that helps). It's frequently used throughout a large codebase. cheetah obviously has a transitive dependency on grass through gazelle.   
In the cheetah conanfile.py we also build a suite of build time tests using gtest as the testing framework, we'll call them `test_cheetah`. The `test_cheetah` application wants to directly use features from `grass`. So `grass` is not a tool but in this case its only explicit consumer is a build time test, that will only build and run when the package is built from source. Is this an abuse of the intent of the `build_requires` function? If so, is there some other way I can accomplish this with tools provided by conan?(It seems like `private` might work, but I think `private` is mostly supplanted by `build_requires`, yes?)

**Comment by puetzk** [comment]
I think this might be the same issue (or at least related)? that @DoDoENT reported (and @thorntonryan also stumbled on) in #4753 (there's a zip with a minimal repo example in that issue that works in 1.12.3 but fails in 1.13+). If so I can elaborate on our use-case; we have **lots** of packages where things that were already in our requires turn up in as transitive dependencies inside our build_requires too.

We generally hit it because we have a lot of DLLs that have extremely narrow and carefully-defined ABI surfaces compared to their implementation (mostly oleautomation COM servers, but sometimes just DLLs where care has been taken about what symbols are exported and what's not). They have correspondingly minimal package_ids (generally os, arch, and little or nothing else), because debug/release, different compilers, even different languages do not matter; we want consumers to match and use one of the handful of tested binaries that we publish to artifactory, and it's fine to have a mix of compilers (or even different languages) in the mix.

These libraries sometimes refer to each other, and we also have a lot of implementation-helper static libraries that are reusable, with a more complete settings in their package_id os, arch, compiler, build_type, cppstd, etc as meaningful variations. Often these static libraries make use of the public APIs, so they declare them as requires.

But when one of these oleatomation libraries uses a static library to help in its implementation, that uses another of the oleatomation libraries, the static library has to be hidden from the public requirements tree, because there's no expectation that it should (or even could) match the settings the consumer is using; it's perfectly acceptable to have a C# caller require and receive an oleautomation DLL that was built with VS2017, that was linked to a (private) static library also built in VS2017), but which made references to another oleautomation library that was built in VS2013, or C#, or whatever.

So a consumer executable1 requires dll2, which build_requires static3, which publicly requires dll4.
dll2 and dll4 have carefully defined interfaces, so semver is completely appropriate; it may very well be that dll2 was built with dll4/1.1.3 and executable1 wants to override that and force the overall tree to choose dll4/1.2.0. This is fine. static3 doesn't matter to the consumer all (it's symbols were completely encapsulated inside dll2 and aren't visible at all) and the profile the caller is building with might be completely incompatible with static3 (e.g. a C# caller invoking functions in a COM dll2 written in C++ can't match any possible settings for a C++ static3; their justoolchain can't do anything with the .lib, but they don't need to since linking happened when building dll2, not when loading/calling it). Or they could still be in C++, but using a completely different compiler or major version of static3.

We have to use build_requirements for this, rather than private requirements, because the latter still tries to resolve them all using the consumer's profile. 

Conan doesn't really *support* this, but it comes closer than anything else we've tried, and we have a reasonably satisfactory solution with it. There are a couple big hassles if you're looking for ways to do even better:
1) There's no way (that I know of) to make a private subtree where "this library, and anything else it requires pull in, uses these settings instead of mine".
2) having used build_requires to get around 1), if we *do* expose things from even further down (e.g. dll2 
returns objects from dll4), so they *do* matter, we have to manually restart the transitive requires, it doens't automatically propagate.
3) we generally have to keep two conanfiles; a conanfile.txt to resolve the build requirements and actually build the library, and a conanfile.py with minimal settings and just the public requires to use with export-package and publish it. This is because the recipe with minimal settings (to choose the right published binary) doesn't contain enough settings to pick our build_requires and compile the package. And the caller's settings would probably be wrong even if we did list them and just delete from self.info.settings in package_id. This is kind of a weaker variation of 1.

**Comment by memsharded** [comment]
Update for @jallenwork: I recommend having a look to https://github.com/conan-io/conan/issues/4753, and specifically to comment https://github.com/conan-io/conan/issues/4753#issuecomment-481663245, it might partially address your questions above.

**Comment by memsharded** [comment]
This issue has been fixed and released in 1.14.3, please @jallenwork update and report. Thanks!

**Comment by jallenwork** [comment]
@memsharded Thanks for the fast turn-around on this! This did fix my test case, but in the larger general case I'm still experiencing link order difference between 1.11.2 and 1.14.3. I'll try to expand my test case to demonstrate the larger case. I'll let you know when I've updated.

**Comment by memsharded** [comment]
Hi @jallenwork 

As you know, Conan 1.14.3 was already released, and we are also working on other related fixes for Conan 1.14.4 here: https://github.com/conan-io/conan/pull/4987. It would be great if you could have a look to them too, and see if your link order issues still persist with that PR. Thanks.
