### ISSUE TITLE
Error on windows builds using conan since last release

### ISSUE THREAD

**Issue by mcraveiro** [conan-io/conan#534]
Hi guys,

My build broke yesterday[1] and it may be related to the latest conan release - well, at least I can't see what I have changed at my side. I see two problems. First I can't find LibXML any longer:

```
...
libiconv/1.14@lasote/stable: Package installed 8c56abc937032ac522fca90cb67e1da0f185cc6e
libxml2/2.9.3@lasote/stable: Installing package 61604682c7a4b22242d96b4a5550c3c33d15eb86
libxml2/2.9.3@lasote/stable: Looking for package 61604682c7a4b22242d96b4a5550c3c33d15eb86 in remote 'conan.io' 
libxml2/2.9.3@lasote/stable: WARN: Binary for 61604682c7a4b22242d96b4a5550c3c33d15eb86 not in remote: Package not found!
ERROR: Can't find a 'libxml2/2.9.3@lasote/stable' package for the specified options and settings
```

Second problem is that even though boost appears to install correctly:

```
Boost/1.60.0@lasote/stable: Installing package ee5dab950b6ea94ae953b93c55343e98c2ec39df
Boost/1.60.0@lasote/stable: Looking for package ee5dab950b6ea94ae953b93c55343e98c2ec39df in remote 'conan.io' 
...
Boost/1.60.0@lasote/stable: Package installed ee5dab950b6ea94ae953b93c55343e98c2ec39d
```

It is not found by CMake:

```
cmake : CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.4/Modules/FindBoost.cmake:1247 (message):
At line:1 char:1
+ cmake C:\projects\dogen\build\scripts\..\.. -DCMAKE_BUILD_TYPE=Releas ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (CMake Error at ...1247 (message)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  Unable to find the requested Boost libraries.
  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:60 (find_package)
-- WIN32 OR WIN64
-- iconv not found
```

Does this ring any bells?

Many thanks for your time.

Marco

[1] https://ci.appveyor.com/project/mcraveiro/dogen/build/2.2.502/job/y0tmvy7v9ui2re4e

**Comment by memsharded** [comment]
Hi @mcraveiro , thanks for reporting.

yes, the first one might be related to: http://docs.conan.io/en/latest/changelog.html

There was a mistake in the hash computation of binaries, many packages have been regenerated for new shas, libxml2 possible has not. Will report @lasote, to see if it could be done.

Meanwhile, you could use ``--build=libxml2`` or keep the old conan 0.12 version.

The second one, don't know what could be failing, will have a look. 

Thanks again!

**Comment by memsharded** [comment]
For the second error, it seems that it is just because of the previous failure, I think it should work if you add the ``--build=libxml2`` to your install command. I will update you when the new package binaries for libxml2 are uploaded.

**Comment by memsharded** [comment]
We haven't forgot about this one, we have been working hard on the underlying issue, and come up with a PR: https://github.com/conan-io/conan/pull/547/files. I hope we can merge it soon, release a minor, and solve these issues. Thanks for your understanding!

**Comment by mcraveiro** [comment]
No problems, and thanks for the update!

**Comment by memsharded** [comment]
Hi Marco! We released 0.13.3, and it may fix your problem, could you please re-launch your build? Thank you!

**Comment by mcraveiro** [comment]
Hi @memsharded great news! :-) I just kicked off a build [1]. Conan version update looks good:

```
Conan version 0.13.3
```

Boost, iconv etc seem to install ok but it's still failing on libxml:

```
ibiconv/1.14@lasote/stable: Package installed 2decb9813b2a0f4bd9cd936c992fde4c68daa772
libxml2/2.9.3@lasote/stable: Installing package 7a25cd8b1ac2aecbe238d2dde413003d91c5add7
libxml2/2.9.3@lasote/stable: Looking for package 7a25cd8b1ac2aecbe238d2dde413003d91c5add7 in remote 'conan.io' 
libxml2/2.9.3@lasote/stable: WARN: Binary for 7a25cd8b1ac2aecbe238d2dde413003d91c5add7 not in remote: Package not found!
ERROR: Can't find a 'libxml2/2.9.3@lasote/stable' package for the specified options and settings
- Try to build from sources with "--build libxml2" parameter
- If it fails, you could try to contact the package author  at 'http://github.com/lasote/conan-libxml2', report your configuration and try to collaborate to support it.
```
I guess the SHA key problem is still present?

Cheers

[1] https://ci.appveyor.com/project/mcraveiro/dogen/build/2.2.540/job/h7b6b3r2jhf0bomx

**Comment by memsharded** [comment]
Oh, yes, the sha problem requires packages to be rebuilt, sorry. I thought you could launch it with --build libxml2. But no worries, will try to kick a libxml2 build, and see if it fixes it. Thanks for trying!

**Comment by mcraveiro** [comment]
Excellent, seems like normal service has resumed! [1] Thanks!

[1] https://ci.appveyor.com/project/mcraveiro/dogen/build/2.2.543

**Comment by memsharded** [comment]
Excellent, thanks for telling!
