### ISSUE TITLE
ConfigureEnvironment is not prepared for paths containing brackets

### ISSUE THREAD

**Issue by mnowy** [conan-io/conan#557]
When you use code like this in your conanfile.py:
```
os.environ["LIB"] = os.getenv("LIB", "") + "\"C:/Program Files (x86)/Microsoft SDKs/Windows/v7.1A/Lib\";"
confEnv = ConfigureEnvironment(self.deps_cpp_info, self.settings)
envVariables = confEnv.command_line
vcvars = tools.vcvars_command(self.settings)
self.run("%s && %s && %s" % ( vcvars, envVariables, build_command)
```

You will end up with error: ```/Microsoft was unexpected at this time.```

Cause of this are brackets in ```Program Files (x86)``` path and line 97 of ConfigureEnvironment.command_line function 
```
command = ("(if defined LIB (SET LIB=%LIB%;{lib_paths}) else (SET LIB={lib_paths}))"
```
I think that brackets from Program Files path are messing with brackets before and after SET command.

You can even reproduce this issue in command line with code:
```
SET LIB=C:/Program Files (x86)/Microsoft SDKs/Windows/v7.1A/Lib
(SET LIB=%LIB%;C:/Users/jenkins/.conan/data/somepath)
```

**Comment by lasote** [comment]
We are currently working in a new implementation of ConfigureEnvironment. @memsharded take a look and verify that this error is already solved. Thanks!

**Comment by memsharded** [comment]
Yes, we have added quotes to those paths, so they should be solved now. 
The full branch and PR is here: https://github.com/conan-io/conan/pull/547/files, if anyone wants to run from sources from that branch to check that the problem is gone, that would be a great test (I have also introduced 2 tests in the suite, but testing with real code is better)

**Comment by memsharded** [comment]
Just released 0.13.3: http://docs.conan.io/en/latest/changelog.html
Please try it to confirm this issue is fixed. Thanks!

**Comment by mnowy** [comment]
Unfortunately still the same problem.

In attachment you can find conanfile.txt with example how to reproduce problem.

Just change extension to .py and run `conan build` on it.
[conanfile.txt](https://github.com/conan-io/conan/files/528143/conanfile.txt)

**Comment by memsharded** [comment]
I checked it, I think the problem is the extra quotes, not necessary. I have tried the following and worked:

```python
current_lib = os.environ.get("LIB", "")
if current_lib:
        current_lib += ";"     
current_lib += "C:/Program Files (x86)/Microsoft SDKs/Windows/v7.1A/Lib\;"
os.environ["LIB"] = current_lib
```

- Actually it didn't build it, it failed because there is no makefile, but that was expected.
- Your code could have some problem with the concatenation if LIB had a value, has it would miss a ``;``
- Please note that the interface of ``COnfigureEnvironment has changed``, now ``envVariables = confEnv.command_line_env`` loads vcvars for the matching visual studio, so no need to manually add any system library to LIB
- You might be interested in seeing the test code we are using to validate the new ``ConfigureEnvironment``, see them here: https://github.com/conan-io/conan/blob/develop/conans/test/utils/cpp_test_files.py#L23 That code works for static, dynamic, with definitions, in C, in C++ and with a dependency tree with a diamond structure. It works in MSVC and also with MinGW.

Please try the above and using the new ``command_line_env`` and tell me if it worked. Thanks very much for your detailed report with code! Very useful.

**Comment by mnowy** [comment]
Your code proposition works fine. Thank you for detailed description of new `ConfigureEnvironment`'s features especially `confEnv.command_line_env` looks very useful.

Thanks!

**Comment by memsharded** [comment]
Thanks to you for keeping track of it and testing! Cheers
