### ISSUE TITLE
[idea] Inheritance specifier for channels

### ISSUE THREAD

**Issue by jasal82** [conan-io/conan#5660]
We have a bunch of profiles that make use of the `build_requires` attribute to directly attach their associated toolchain which we also deploy as a Conan package (see https://github.com/conan-io/conan/issues/5059 for reference). These profiles are aggregated in another Conan package that users can deploy on their machine which helps us keep the profiles consistent. Distributing them via `config install` is not an option because then they'd be versioned together with the other more environment-specific settings which is not what we want.

All of our packages live either in the `dev` or the `release` channel. The `dev` channel serves as snapshot channel where a continous deployment job uploads nightly recipe snapshots that users can depend on using version ranges. The `release` channel is reserved for the final releases.

What we need to do now is to update the build requirement attribute in all of the profiles to `toolchain_name/version@sick/release` before a release, tag a version and then reset the channel name back to `dev`. This is very inconvenient and also unnecessary because Conan has all the information to do that automatically. We just need a way to tell Conan that it should inherit the channel from the parent.

My proposal would be to allow something like `pkg/version@user/=` or `pkg/version@user/[inherit]` to make Conan use the parent's channel. I know that there is already the possibility to define the channel dynamically in `conanfile.py` but as far as I know there is no way of doing that in `conanfile.txt` or profiles. You can always use a `conanfile.py` instead of the `.txt` but for profiles I don't see an easy way of solving this. What do you think?

**Comment by memsharded** [comment]
>  These profiles are aggregated in another Conan package that users can deploy on their machine which helps us keep the profiles consistent. Distributing them via config install is not an option because then they'd be versioned together with the other more environment-specific settings which is not what we want.

Not fully clear, if you put the profiles in a conan package, they will still be versioned together. Also, you can have multiple origins for ``conan config install`` you can use one for profiles and another for other things, and they don't need to be even of the same type (you can put profiles in a zip, and other things in a git repo).

> All of our packages live either in the dev or the release channel. The dev channel serves as snapshot channel where a continous deployment job uploads nightly recipe snapshots that users can depend on using version ranges. The release channel is reserved for the final releases.

We are currently suggesting, based on multiple users feedback, that the promotions that were implemented by channels might be better implemented by using different remote repositories. Like having a remote called "dev" and another called "release". This has some implications:

- It is possible to achieve one of the important principle of devops: to only build once. Otherwise, the "release" packages have to be rebuilt if we want to achieve full consistency of information (``conan copy`` doesn't migrate metadata).
- It will work better with lockfiles and revisions (revisions are also important for Artifactory topologies with remote and virtual repositories).
- Different ``package_id`` modes that include the user/channel will not be affected by promotions, and those binary ``package_id`` will remain constant between the dev and release pipelines, which helps a lot with traceability.

Have you considered this approach?

**Comment by jasal82** [comment]
I guess that could work but I'm wondering how you'd then be able to choose between release or development packages on the dependency level. That would require either an alias command with remote selection or (better) some way of overriding dependency information on consumer level, e.g. a file with rules that select the remote for certain packages.

**Comment by jasal82** [comment]
Probably it would be best if the user/channel information was removed entirely from the requires and injected during the package creation somehow instead.

**Comment by jasal82** [comment]
Just an idea, but maybe something like this could work: The consumer (and all transitive dependencies) require without user/channel

```
requires = "LibA/[2.x]", "LibB/[*]"
```

By default these are resolved on the pre-configured 'release' remote but you can override it by specifying another remote on a per-package basis in a config file that you pass to the package creation commands `conan create . -depconf=deps.conf`. The config file could be something like

```
*: release
LibA: develop
```

Or even the other way around because usually you'll be working in the develop branch and releases are a special case.

**Comment by memsharded** [comment]
Hi @jasal82 

> Probably it would be best if the user/channel information was removed entirely from the requires. The package resolving strategy should be injected during the package creation somehow instead.

have you checked the latest release notes from 1.18? user/channel is becoming optional. Still not very documented or spread, we want to make sure that nothing is broken with this change first, before promoting it more.

The idea is that packages are resolved against different remotes. You use one or other remotes depending on what you want to do. Packages are NOT mixed from different remotes,  specially dev/release remotes, but instead, all the packages, including transitive dependencies are promoted between repos. Artifactory makes this process efficient because deduplicated storage.

**Comment by jasal82** [comment]
I understand the promotion mechanism, it's an integral part of our new Conan-based build infrastructure. I didn't know that metadata is not migrated in that process, that was a very useful comment because now I have to redesign our release process.

Now to the mixing of different remotes: I think that this is an essential feature. In my example above I want to build the consumer with features from LibA that haven't been released yet. A recipe for the HEAD of the LibA develop branch has been exported by CI to the Conan `dev` remote. I'd like to keep all other dependencies on the release packages. How would I do that without mixing remotes?

**Comment by memsharded** [comment]
> I understand the promotion mechanism, it's an integral part of our new Conan-based build infrastructure. I didn't know that metadata is not migrated in that process, that was a very useful comment because now I have to redesign our release process.

Just in case, I am talking about the ``conan copy`` way of changing the user/channel of a Conan package. Yes, the ``conaninfo.txt`` that is inside packages is not modified (it would break the manifests otherwise, and the revisions too...)

> Now to the mixing of different remotes: I think that this is an essential feature. In my example above I want to build the consumer with features from LibA that haven't been released yet. A recipe for the HEAD of the LibA develop branch has been exported by CI to the Conan dev remote. I'd like to keep all other dependencies on the release packages. How would I do that without mixing remotes?

A flow that we are now maturing would be something like:
- There is a "develop" repo, that captures the current state of development, and a "release" repo that is what is used in production.
- When a developer does changes to LibA, they are built and validated all against the "develop" repository. It might require re-building packages that depend on LibA too. Typically, for avoiding unrelated changes, a lockfile would be captured at the moment of starting to build those changes to LibA.
- Temporary packages from builds are stored in a "build" repository, so they do not affect the "develop" repository until accepted.
- When those changes to LibA are accepted (lets say, the source code changes are merged into develop), then the packages resulting from that build can be actually copied/moved to the develop repository, so other developers and build will start using them.
- The "develop" repository might at any time be promoted to "release" (maybe first to "staging" or "testing" repo if there are extended tests pre-production). All the latest artifacts/packages in develop can be promoted, or maybe those defined by the last lockfiles (in that case it is necessary to store them)

Please let me know if this makes sense. Also, if you'd like, it might be possible to chat on CppLang slack if you are there, drop us a line at info@conan.io if you want. Thanks!

**Comment by KerstinKeller** [comment]
@memsharded one question, will you actually be deprecating the "user/channel" notation for the future?

We're still in the process of adopting Conan and our workflows are not yet fixed, but it will be important to know, because right now we're sketching out the workflows to make use of "user/channel".

E.g. nightly builds would publish to `user/ci`, then alpha releases to `user/testing` and then finally to `user/stable`. However I am concerned if providing version ranges  (`libB/[>=1.0.0]`)with this new kind of flow, a `libA/2.0.0@user/ci` package could rely on a `libB/1.1.0_beta@user/ci` and then be promoted to `libA/2.0.0@user/testing` though it depends on an unstable beta version. If you pin the user and channel, this cannot happen.

If you integrate many packages dynamically, you might want to have this behavior and then release all at once. But in other cases you want to depend on released versions only.

And how does that relate with the local cache concept? For heavy builds it's important that the binaries stay located in the local cache. If there are no channels, how do we mirror the different remotes? Does that mean that on the local Cache level, all packages need to be stored duplicated?

**Comment by memsharded** [comment]
> @memsharded one question, will you actually be deprecating the "user/channel" notation for the future?

No, they will always be there, but optionally, to be used when someone wants to explicitly put packages under a different username or channel, to make it explicit, or to disambiguate in different use cases. Just they will not be mandatory for users that they don't need to use them.

**Comment by lasote** [comment]
Please @memsharded refresh here exactly what we want to investigate. Thanks!

**Comment by jasal82** [comment]
I think the important question is how can we mix dependencies from different channels (develop/release) in a single dependency graph while at the same time allowing binary package promotion across channels. This is a hard requirement for us because users may need certain new features on a component for which there is no release yet. Switching repositories is not a valid solution because it prevents a consumer from depending on A/develop and B/release at the same time.
During a package release phase we want to

1. Create a release branch of the sources in Git (which also contains our conanfile.py)
2. Fix all its dependencies to release channel, ideally without having to commit anything so that it can be done solely via build job injection; this cannot be done by globally switching to a release-only repository because we would have to adapt the channel names then
3. Build release candidates, push binary packages to the staging channel and test them until satisfied
4. Create a tag on the Git repo (source method in conanfile is not used but instead we rely on SCM auto capturing so we don't have to change anything in the recipe)
5. Promote the final (tested) RC binary package from the staging channel to the release channel without having to rebuild it

The problematic steps (where we are missing support from Conan) are step 2 and step 5.

For step 2 we would need one of these options:
- The possibility to override user/channel for all dependencies in the graph via command line parameter or configuration file.
- A channel inheritance mechanism as outlined in my initial post, but after giving it some more thought I think it might not be sufficient and the first option would be the better choice.
- Selective remote mapping for different channels, i.e. some kind of mapping which instructs conan to resolve packages in develop channel on remote A, packages in release channel on remote B. The actual packages on the individual remotes must not have a user/channel set then, however. We'd still have to change the conanfile in this case, so I'd rather tend to the first option again.

For step 5 the promotion of binary packages must work across channels. As far as I understood the metadata is not updated correctly. I'm not sure what that means in practice and if it would affect our build process at all.

**Comment by jasal82** [comment]
Meanwhile we've found workarounds for the problems mentioned here so I'll close this issue. We can discuss possible improvements in the context of Conan 2.0 tribe.
