### ISSUE TITLE
[question] How to upload package with same recipe but different package ID from different client

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#7230]
So, I built a package on a Linux machine, and also  built the same package using the same recipe file on a Windows machine, 
After i upload the Linux package to my artifactory by `conan upload pkg/ver@usr/channel --all -r=remote_name`, i would also put the windows version to the same repository. so i run the same command on the windows client, but i got error message saying:
Error uploading file: conan_export.tgz, '500: Not enough permissions to overwrite artifact ...
Error uploading file: conanfile.py, (same error)
Error uploading file: conanmanifest.txt, (same error)

The quesiton i dont want to upload these files, but only the package that is built for windows platform, is there a way to do that? tried `-p` but seems the same issue. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @shelper 

It looks like that you have a difference in your recipe exported files, and that is forbidding you to upload it. This is an expected behavior, and is a protection against inconsistencies. You can only upload new binaries for a recipe if the recipe is indeed the same, otherwise it would be problematic, having binaries that were not created with that recipe.

The most common reason for this is having source control, like git, changing the line endings CRLF, LF in different platforms. Please make sure that your checkout is exactly the same, the conanfile.py, conanmanifest.txt, etc will be the same files, with the same checksum, and it should be able to work without problems.

Please let me know if that was the reason.

**Comment by shelper** [comment]
by copying the export folder from linux to windows solve the problem. just like you said, it is the line ending difference on windows and linux causes the problem. 

Considering there are people working on different platforms for the same reciple, i wonder if there is a way in conan to solve the problem. e.g., add a switch in `conan.conf` for converting from Windows-style to UNIX-style line endings before uploading to the repo?

**Comment by TheQwertiest** [comment]
@shelper , usually this is solved by centralized publishing, e.g. CI. Since otherwise it's hard to guarantee any environment consistency (e.g. one person published using gcc5 from Ubuntu, another - gcc5 from Debian, hence resulting packages might be incompatible).

**Comment by memsharded** [comment]
> Considering there are people working on different platforms for the same reciple, i wonder if there is a way in conan to solve the problem. e.g., add a switch in conan.conf for converting from Windows-style to UNIX-style line endings before uploading to the repo?

Yes, we have consider this, but it is more complicated than it seems. Conan could try to normalize all files, but that opens a new can of worms:
- Is the normalization of Conan always wanted? Sure there aren't some files which line endings are important to preserve? I can almost guarantee that some users will need to preserve them as-is
- What files? There are some recognizable text extensions, but what if there are files that have different line endings that don't have extension? Some files might be normalized by git, because of git own config.

So after all, it seems just postponing and hiding more the problem, but not really solving it. So we recommend to solve that issue at the source level, and that is mostly managed better by the SCM, not Conan.

**Comment by shelper** [comment]
> @shelper , usually this is solved by centralized publishing, e.g. CI. Since otherwise it's hard to guarantee any environment consistency (e.g. one person published using gcc5 from Ubuntu, another - gcc5 from Debian, hence resulting packages might be incompatible).

@TheQwertiest  yeah, I agree, but i think this does not solve the issue of windows/linux line ending.
I wonder if a solution for this line ending issue can be solved by the conan hooks, basically adding a hook for windows system to always convert line ending to unix style `pre-export`
Is there such a hook file available? it is trivial to write one but i just want to make sure every potential file/folder is covered.

**Comment by shelper** [comment]
add following as a hook and seems to work for me, just for anyone who has similar issue, i am also closing this as solved
```python
import os

from conans import tools

def post_export(output, conanfile, conanfile_path, reference, **kwargs):
    if tools.os_info.is_windows:
        output.warn("Converting exported file to Unix style line ending")
        for export_file in os.scandir(os.path.dirname(conanfile_path)):
            tools.dos2unix(export_file.path)
```

**Comment by jgsogo** [comment]
Great! I'm closing the issue then, feel free to open it if something else needs to be added.
