### ISSUE TITLE
ERROR: Value provided for channel, '0' (type str), is too short. Valid names must contain at least 2 characters..

### ISSUE THREAD

**Issue by coder-ent** [conan-io/conan#7336]
We encountered an error message while using the conan search command with one of our remote packages hosted on JFrog Artifactory. 

Conan seems to interpret a channel with the name "0" but we did not create this and is not visible on the Artifactory web interface. We only have two channels "stable" and "testing". 

Apart from that conan also seems to interpret one package each under the two existing channels with the ID "0" which are again not visible in the web interface. 

Other commands such as conan download and conan remove also don't work for this package beacause of the same root cause, we assume. [ERROR: Binary package not found: 'adtf2_package/2.14.3@sep/stable:0']

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Conan version: 1.18.1

### Logs (Executed commands with output) (Include/Attach if Applicable)
Screenshots attached
![Wrong_package](https://user-images.githubusercontent.com/63263453/87668132-d8be4e00-c76b-11ea-9fe2-9b1499454446.png)
![conan_search](https://user-images.githubusercontent.com/63263453/87135020-c50d7600-c299-11ea-86f4-730d0fb89611.png)

**Comment by czoido** [comment]
Hi @coder-ent,

Could you please test this using the latest patch for Conan 1.18: 1.18.6 ?
I think that error could be related to a fix released in 1.18.2.
Also, one question: Are you using alias for packages?

**Comment by czoido** [comment]
Two more questions:
- Which Artifactory version are you using?
- Did you modify the layout of the repository in Artifactory?

**Comment by coder-ent** [comment]
Hi @czoido 
Thank you for the quick response. 

1. Updating to conan 1.18.6 did not help. I still get the same error. 
![image](https://user-images.githubusercontent.com/63263453/87142733-428ab380-c2a5-11ea-8d2a-fc03b4f2aa7b.png)
2. We do not use aliases for packages in the packge as far as I know, definitely not for this package. 
3. Artifactory version is 6.20.0
4. The project is part of a large organisation and Artifactory is managed by a central IT team. I could ask around if the layout was modified but the appearance hasn't changed in my knowledge during the last few months.

**Comment by memsharded** [comment]
Just to make sure, I have just tested with Conan 1.28 and Artifactory 6.20, but couldn't reproduce this error, everything seems to be working fine in my end.

A few things that could be tried:
- Check if this happens for all packages there, or only for those 2
- What happens if you create ``conan new hello/0.1 -s`` + ``conan create . user/testing`` + ``conan upload * -r=xxx --all --confirm``?
- Download and paste here the contents of the ``index.json`` file.
- Current config: ``conan config get``

**Comment by coder-ent** [comment]
It happens only for these two packages, not in any of the 50+ other packages we have in the project. 
![hello](https://user-images.githubusercontent.com/63263453/87291402-8da00300-c4ff-11ea-9185-9cf099d050d1.jpg)

index.json:
[index_json.txt](https://github.com/conan-io/conan/files/4911688/index_json.txt)

conan config:
![image](https://user-images.githubusercontent.com/63263453/87291492-b0cab280-c4ff-11ea-9b60-0bd72acff870.png)

**Comment by memsharded** [comment]
Hi @coder-ent 

It seems something went bad on the Artifactory side, something was corrupted in the database/filestore.
If you are a JFrog customer, I would suggest to file a support ticket (and letting us know). Otherwise, please let me know:

- Artifactory edition: CE, PRO, Enterprise...
- Artifactory run environment.
- Which DB backend are you using.
- Any other specific details, like if it is a High Availability setup or something like that.

If you can't disclose some of those details in public, you can also write to info@conan.io

Many thanks!

**Comment by coder-ent** [comment]
Hello @memsharded 

I shall try to get it resolved via JFrog Support. Thanks for your help!

**Comment by memsharded** [comment]
Ok, many thanks @coder-ent, if you can, please let us know how it goes, or if you need our help from our side, reopen the issue.  If you have also a JIRA ticket, please copy it here, so we can track it too. Thanks!
