### ISSUE TITLE
[bug] self.conan_data is not loaded when using a custom version.

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#8160]
conan create command fails with an error 
```
ERROR: expected-lite/0.2.0-1: Error in source() method, line 18
	tools.get(**self.conan_data["sources"][self.upstream_version])
	KeyError: 'sources'
```
if the package version is not found in `conandata.yml`

### Environment Details (include every applicable attribute)
  * Operating System+version: MacOS Catalina 10.15.7
  * Compiler+version: clang 12.0
  * Conan version: 1.32.0
  * Python version:  3.8.6

### Steps to reproduce (Include if Applicable)

- Create a conanfile.py with the content below:

```
import os
from conans import ConanFile, tools, python_requires


class ExpectedLiteConan(ConanFile):
    name = "expected-lite"
    upstream_version = "0.2.0"
    version = "0.2.0-1"
    settings = "compiler"
    no_copy_source = True

    @property
    def _source_subfolder(self):
        return "source_subfolder"

    def source(self):
        print(str(self.conan_data))
        tools.get(**self.conan_data["sources"][self.upstream_version])
        extracted_dir = self.name + "-" + self.upstream_version
        os.rename(extracted_dir, self._source_subfolder)

    def build(self):
        pass

    def package(self):
        pass
``` 

- Create a conandata.yml with the content below:
```
sources:
  "0.2.0":
    url: https://github.com/martinmoene/expected-lite/archive/v0.2.0.tar.gz
    sha256: 3cd85c1dc0e0ad0ee6eed301847d7f0a972a200dc6f77afa23cb0e40aa9134bc
```
- run the command `conan create .` and will get an error
```
ERROR: expected-lite/0.2.0-1: Error in source() method, line 18
	tools.get(**self.conan_data["sources"][self.upstream_version])
	KeyError: 'sources'
```

PS: everything works as expected if you change version from `version = "0.2.0-1"` to `version = "0.2.0"`

**Comment by memsharded** [comment]
Hi @boussaffawalid 

I am not sure what is happening, I have implemented a test following your report, and it works correctly. This passes and downloads the sources correctly. There should be something else, maybe is there something in the environment or that is not captured in the report? Can you try to reproduce with the minimal unit-test that I am providing?

```python
    def test_different_version(self):
        # https://github.com/conan-io/conan/issues/8160
        client = TestClient()
        conanfile = textwrap.dedent("""
            from conans import ConanFile, tools

            class ExpectedLiteConan(ConanFile):
                name = "expected-lite"
                upstream_version = "0.2.0"
                version = "0.2.0-1"

                def source(self):
                    print(str(self.conan_data))
                    tools.get(**self.conan_data["sources"][self.upstream_version])
                """)
        conandata = textwrap.dedent("""\
            sources:
              "0.2.0":
                url: https://github.com/martinmoene/expected-lite/archive/v0.2.0.tar.gz
                sha256: 3cd85c1dc0e0ad0ee6eed301847d7f0a972a200dc6f77afa23cb0e40aa9134bc
            """)
        client.save({"conanfile.py": conanfile,
                     "conandata.yml": conandata})
        client.run("create .")
        print(client.out)
```

**Comment by boussaffawalid** [comment]
@memsharded the test succeeded on my environment as well but `conan create .` is still failing.

BTW: I tried with a windows machine and everything works as expected, so either:
* something is wrong with my mac environment.
* issue is only reproducible on mac environment.

**Comment by memsharded** [comment]
I have submitted https://github.com/conan-io/conan/pull/8173, to see what it says in OSX CI

**Comment by memsharded** [comment]
Hi @boussaffawalid 

The CI (including OSX) seems to pass the test successfully: https://conan-ci.jfrog.info/blue/organizations/jenkins/ConanTestSuite/detail/PR-8173/1/pipeline

Exactly the test above is failing when you run it in your OSX machine?

**Comment by boussaffawalid** [comment]
The test above **passes** on my OSX machine. However, when I run the command `conan create .` it fails.

**Comment by memsharded** [comment]
Hi @boussaffawalid 

I am not sure I follow. The test above contains a ``conan create .``. Where are you running such ``conan create . `` command? Saving the above code manually in a folder and running it?

**Comment by memsharded** [comment]
I would try  printing the ``self.conan_data`` in the recipe, before it fails, to see if it has some info that could help us identify the problem

**Comment by boussaffawalid** [comment]
I did that already, and it is empty. 
The issue happened when I created a conanfile.pt and conandata.yml
Please check https://asciinema.org/a/xCjo1AypFbCj6p6K6c6f8IQ2c

**Comment by memsharded** [comment]
That really helped!

The issue is that you are running the ConanCenter hooks. One of them is designed to strip the ``conandata.yml`` information, so for previous versions you get always the same revisions, even if you are adding new information to the ``conandata.yml``, that otherwise would be exported as a new thing and generate a new revision, which is really undesired in ConanCenter, as it would require to build all previous versions when creating a new version.

You can fix this deactivating this hook, or if you plan to do something similar to ConanCenter you could tune it for your purpose.

**Comment by boussaffawalid** [comment]
ohh! now it make sense, thank you!

**Comment by memsharded** [comment]
Good, now we know what was happening, this was not a bug, but expected behavior of running that hook. I think this issue can be closed.
