### ISSUE TITLE
[bug] Unable to connect to osp=https://osp.jfrog.io/artifactory/api/conan/conan-public

### ISSUE THREAD

**Issue by StanleyYoo** [conan-io/conan#8459]
Hi, I try to build conan configuration and it keep reading following log at git bash:

$ conan install . -u -s build_type=Release -g virtualrunenv
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

libcosimc/0.8.0@osp/testing: Not found in local cache, looking in remotes...
libcosimc/0.8.0@osp/testing: Trying with 'conan-center'...
libcosimc/0.8.0@osp/testing: Trying with 'osp'...
ERROR: HTTPSConnectionPool(host='osp.jfrog.io', port=443): Max retries exceeded with url: /artifactory/api/conan/conan-public/v1/ping (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))

Unable to connect to osp=https://osp.jfrog.io/artifactory/api/conan/conan-public
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.

Could you please support this issue?

**Comment by solvingj** [comment]
The fact that the URL of your remote ends in `.jfrog.io` indicates you are trying to connect to a private artifactory cloud instance.  Was it working for you in the past, or are you trying to set it up for the first time?

**Comment by StanleyYoo** [comment]
Hi and thanks for the response. No this is the first set by following the read.md. Need your support.

**Comment by solvingj** [comment]
Did you configure the remote with credentials?

**Comment by StanleyYoo** [comment]
It didn't ask me any credentials, i.e. password or ID.

**Comment by memsharded** [comment]
Hi @StanleyYoo 

We need to know the Conan version, the OS you are running, and how did you install Conan (pip, installer, etc). There are some known issues with SSL in OSX (not Conan, but dependencies), that might be solved upgrading Conan or its dependencies:

- Do you have the same issue connecting to that server from other machines?
- Do you have the same issue connecting to that server from other OSs?

**Comment by solvingj** [comment]
You need to add your username and password when you do the `conan remote add` command.

**Comment by StanleyYoo** [comment]
My Conan version is 1.33.1 and installed via pip. OS is Windows 10 with a version of 10.0.18362. I haven't tried to connect to that server with other machine and OS.

**Comment by StanleyYoo** [comment]
I tried to remove and add again as below but it didn't ask me any credential. Did I do in a wrong way?


SEUYOO@PUSLA492 MINGW64 /c/Software/OSP

$ conan remote list
conan-center: https://conan.bintray.com [Verify SSL: True]
osp: https://osp.jfrog.io/artifactory/api/conan/conan-public [Verify SSL: True]

SEUYOO@PUSLA492 MINGW64 /c/Software/OSP
$ conan remote list_ref

SEUYOO@PUSLA492 MINGW64 /c/Software/OSP
$ conan remote remove osp

SEUYOO@PUSLA492 MINGW64 /c/Software/OSP
$ conan remote list
conan-center: https://conan.bintray.com [Verify SSL: True]

SEUYOO@PUSLA492 MINGW64 /c/Software/OSP
$ conan remote add osp https://osp.jfrog.io/artifactory/api/conan/conan-public

SEUYOO@PUSLA492 MINGW64 /c/Software/OSP
$ conan remote list
conan-center: https://conan.bintray.com [Verify SSL: True]
osp: https://osp.jfrog.io/artifactory/api/conan/conan-public [Verify SSL: True]

**Comment by memsharded** [comment]
> ERROR: HTTPSConnectionPool(host='osp.jfrog.io', port=443): Max retries exceeded with url: /artifactory/api/conan/conan-public/v1/ping (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))

It is not a credentials thing. It is failing way before getting to the authentication part, it cannot stablish connection because SSL certificates. It is a certificate issue (or the python library Conan is using might not be getting certificates fine). In order to figure out what is the problem, the first step would be to try from a different machine, better if it can be another operating system. If it works in other machine, it is an issue with the certificates in that Windows machine. Next step is to know if there are any special configuration in that machine. Is it a company computer that might have installed different things like VPNs, or custom certificates?

**Comment by solvingj** [comment]
@StanleyYoo are you still having difficulty with your connection?

**Comment by smitalpatil234** [comment]
hello 
I am also facing same issue. while other developers are not facing this issue. (We all uses ubantu )
also I am unable to upgrade conan package(currently I am using 1.36.0 and python 2.7) 
how to check for custom certificates or any special configuration ?

**Comment by memsharded** [comment]
There was recently a certificate that expired, you can check https://github.com/conan-io/conan/issues/9695 (there is a new certificate that can be installed with ``conan config install``, or upgrading)

Regarding your versions, you really need to move to Python3, as Python 2.7 is very deprecated, it will be completely removed from Conan very soon (it has already been removed in Conan 2).

**Comment by smitalpatil234** [comment]
@memsharded Issue is resolved. Issue was with my remote machine, It was unable to connect with internet.

**Comment by memsharded** [comment]
Ok, good, then I am closing this, thanks for the feedback!

**Comment by dipustm** [comment]
Hi,

I am using Conan version 1.45.0 but still getting ERROR
"Uploading to remote 'dev_testing':
Uploading hcl/0.2@origin/nav_int to remote 'dev_testing'
ERROR: hcl/0.2@origin/nav_int: Upload recipe to 'dev_testing' failed: HTTPSConnectionPool(host='rb-cmbinex-hi-d01.de.bosch.com', port=443): Max retries exceeded with url: /artifactory/ehorizon-conan/v1/ping (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
Unable to connect to dev_testing=[https://rb-cmbinex-hi-d01.de.bosch.com:443/artifactory/ehorizon-conan/](https://rb-cmbinex-hi-d01.de.bosch.com/artifactory/ehorizon-conan/)
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.

ERROR: Errors uploading some packages"

Could you please help me with this error?

**Comment by dipustm** [comment]
Result of conan remote:-
conan remote list
conancenter: https://center.conan.io/ [Verify SSL: True]
dev_testing: https://rb-cmbinex-hi-d01.de.bosch.com/artifactory/api/conan/ehorizon-conan-repos [Verify SSL: True]

**Comment by memsharded** [comment]
Hi @dipustm 

It could be a few things:

- You installed 1.45 as an upgrade, and it didn't migrate the Conan cache certificates file. Try removing from your cache the ``cacert.pem`` file and try again.
- There is something else in your system (you would need to report OS, version, Python version, how you installed Python and Conan), that is having issues with the certificate. A first step is trying in another machine.
